### ISSUE TITLE
MissedMetadataKeyInLoggerConfig breaks with `metadata: :all`

### ISSUE THREAD

**Issue by cpiemontese** [rrrene/credo#1033]
### Environment

* Credo version (`mix credo -v`): 1.7.0
* Erlang/Elixir version (`elixir -v`): Elixir 1.14.2 (compiled with Erlang/OTP 25)
* Operating system: Ubuntu 22.04.2 LTS

### What were you trying to do?

I'm having trouble updating to 1.7.0 from 1.6.7 in my company's project, so I created a new project using `mix new`, and modified the initial dummy file to try and reproduce the error.

```elixir
defmodule Tmp do
  require Logger

  @moduledoc """
  Documentation for `Tmp`.
  """

  @doc """
  Hello world.

  ## Examples

      iex> Tmp.hello()
      :world

  """
  def test do
    Logger.debug("Test", a: 1, b: 2)
  end
end
```

My `mix.exs` is

```elixir
defmodule Tmp.MixProject do
  use Mix.Project

  def project do
    [
      app: :tmp,
      version: "0.1.0",
      elixir: "~> 1.14",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      {:credo, "~> 1.7", only: [:dev, :test], runtime: false}
    ]
  end
end
```

And my `config.exs` and `dev.exs`

```elixir
# config.exs

import Config

config :logger, :console, metadata: :all
config :logger, level: :info

import_config "#{config_env()}.exs"

# dev.exs

import Config
config :logger, level: :debug
```

### Expected outcome

I ran `mix credo -a --strict` and expected a positive outcome.

### Actual outcome

I got

```bash
❯ mix credo -a --strict
Checking 3 source files ...
Error while running Elixir.Credo.Check.Warning.MissedMetadataKeyInLoggerConfig on lib/tmp.ex

12:52:50.663 [error] Task #PID<0.385.0> started from #PID<0.379.0> terminating
** (FunctionClauseError) no function clause matching in Keyword.drop/2
    (elixir 1.14.2) lib/keyword.ex:1223: Keyword.drop([a: 1, b: 2], :all)
    lib/credo/check/warning/missed_metadata_key_in_logger_config.ex:126: Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.issue_for_call/4
    lib/credo/check/warning/missed_metadata_key_in_logger_config.ex:59: Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.traverse/3
    (elixir 1.14.2) lib/macro.ex:614: Macro.do_traverse/4
    (stdlib 4.0) lists.erl:1462: :lists.mapfoldl_1/3
    (elixir 1.14.2) lib/macro.ex:620: Macro.do_traverse/4
    (stdlib 4.0) lists.erl:1462: :lists.mapfoldl_1/3
    (stdlib 4.0) lists.erl:1463: :lists.mapfoldl_1/3
Function: #Function<4.89174419/0 in Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.do_run_on_all_source_files/3>
    Args: []
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Keyword.drop/2
        (elixir 1.14.2) lib/keyword.ex:1223: Keyword.drop([a: 1, b: 2], :all)
        lib/credo/check/warning/missed_metadata_key_in_logger_config.ex:126: Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.issue_for_call/4
        lib/credo/check/warning/missed_metadata_key_in_logger_config.ex:59: Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.traverse/3
        (elixir 1.14.2) lib/macro.ex:614: Macro.do_traverse/4
        (stdlib 4.0) lists.erl:1462: :lists.mapfoldl_1/3
        (elixir 1.14.2) lib/macro.ex:620: Macro.do_traverse/4
        (stdlib 4.0) lists.erl:1462: :lists.mapfoldl_1/3
        (stdlib 4.0) lists.erl:1463: :lists.mapfoldl_1/3
```

### My 0.5 cents

It seems like `credo` is breaking with the `:all` metadata option, which should be valid as specified [here](https://hexdocs.pm/logger/1.14.3/Logger.Backends.Console.html#module-options)

**Comment by Nezteb** [comment]
The docs suggest you can skip a check via config: https://hexdocs.pm/credo/check_params.html
> `params` can be either `false`, to disable the check ...
> ```elixir
> # This check won't be part of the analysis
> {Credo.Check.Consistency.TabsOrSpaces, false}
> ```

I tried skipping this specific check via config:
```elixir
# .credo.exs
{Credo.Check.Warning.MissedMetadataKeyInLoggerConfig, false}
```
But that doesn't seem to bypass the error. Do only some checks support a `false` param?

**Comment by rrrene** [comment]
This should be fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by cpiemontese** [comment]
I can confirm that the issue is solved, thanks :pray:
