### ISSUE TITLE
Error while running Elixir.Credo.Check.Warning.MissedMetadataKeyInLoggerConfig

### ISSUE THREAD

**Issue by Vovchikan** [rrrene/credo#1053]
### Environment

* Credo version (`mix credo -v`): 1.7.0-ref.master.f0fada2+uncommittedchanges
* Erlang/Elixir version (`elixir -v`): 25.0.4 / 1.14.1-otp-25
* Operating system: Debian 11

### What were you trying to do
`mix credo lib/failed_offers/decoder.ex`

### Expected outcome
Not crushing?

### Actual outcome
```
10:09 $ mix credo lib/failed_offers/decoder.ex 
Checking 1 source file ...
Error while running Elixir.Credo.Check.Warning.MissedMetadataKeyInLoggerConfig on lib/failed_offers/decoder.ex

10:09:53.067 [error] Task #PID<0.265.0> started from #PID<0.263.0> terminating
** (FunctionClauseError) no function clause matching in Keyword.drop/2
    (elixir 1.14.1) lib/keyword.ex:1223: Keyword.drop([json_file_path: {:json_file, [line: 20, column: 27], nil}, error_reason: {:reason, [line: 21, column: 25], nil}], :all)
    lib/credo/check/warning/missed_metadata_key_in_logger_config.ex:126: Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.issue_for_call/4
    lib/credo/check/warning/missed_metadata_key_in_logger_config.ex:59: Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.traverse/3
    (elixir 1.14.1) lib/macro.ex:635: anonymous fn/4 in Macro.do_traverse_args/4
    (stdlib 4.0.1) lists.erl:1462: :lists.mapfoldl_1/3
    (elixir 1.14.1) lib/macro.ex:600: Macro.do_traverse/4
    (stdlib 4.0.1) lists.erl:1462: :lists.mapfoldl_1/3
    (stdlib 4.0.1) lists.erl:1463: :lists.mapfoldl_1/3
Function: #Function<4.89174419/0 in Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.do_run_on_all_source_files/3>
    Args: []
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Keyword.drop/2
        (elixir 1.14.1) lib/keyword.ex:1223: Keyword.drop([json_file_path: {:json_file, [line: 20, column: 27], nil}, error_reason: {:reason, [line: 21, column: 25], nil}], :all)
        lib/credo/check/warning/missed_metadata_key_in_logger_config.ex:126: Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.issue_for_call/4
        lib/credo/check/warning/missed_metadata_key_in_logger_config.ex:59: Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.traverse/3
        (elixir 1.14.1) lib/macro.ex:635: anonymous fn/4 in Macro.do_traverse_args/4
        (stdlib 4.0.1) lists.erl:1462: :lists.mapfoldl_1/3
        (elixir 1.14.1) lib/macro.ex:600: Macro.do_traverse/4
        (stdlib 4.0.1) lists.erl:1462: :lists.mapfoldl_1/3
        (stdlib 4.0.1) lists.erl:1463: :lists.mapfoldl_1/3
```

`lib/failed_offers/decoder.ex`:
```elixir
defmodule FailedOffers.Decoder do
  use Common
  alias FailedOffers.FailedOffer
  alias FailedOffers.Errors.{MsisdnNotFound, ReasonNotFound, TimestampNotFound}

  @json_file "priv/failed_offers/data/failed_loan_offers_20230621130242.json"
  @type decode_errors :: decode_line_errors()
  @type decode_line_errors :: Errors.MsisdnNotFound | Errors.ReasonNotFound | Errors.TimestampNotFound

  @spec decode_file(String.t) :: list(FailedOffer.t) | [] | no_return()
  def decode_file(json_file \\ @json_file) do
    File.open(json_file)
    |> MonEx.map(
        fn file ->
          process_file(file)
        end
      )
    |> Result.fallback(fn error(reason) ->
        Logger.error("Error in decoding file!",
          json_file_path: json_file,
          error_reason: reason)

        ok([])
      end)
    |> Result.unwrap()
  end

  defp process_file(file) do
    process_file(file,
      IO.read(file, :line), [])
  end

  defp process_file(file, :eof, acc) do
    File.close(file)
    Logger.info("File close!",
      file_path: file)
    acc
  end
  defp process_file(file, line, acc) do
    decoded_line = decode_line!(line)
    Logger.debug("DBG !!! in process_file",
      decoded_line: decoded_line)

    process_file(file,
      IO.read(file, :line), [decoded_line | acc])
  end

  @spec decode_line!(String.t) :: FailedOffer.t | no_return
  def decode_line!(line) do
    ok(message) =
      Jason.decode!(line)
      |> get_message_from_decoded_line()

    %FailedOffer{
      msisdn: get_msisdn(message) |> Result.unwrap(),
      reason: get_reason(message) |> Result.unwrap(),
      timestamp:
        get_timestamp(message)
        |> MonEx.map(&Ecto.Type.cast(:utc_datetime_usec, &1))
        |> Result.unwrap() # double unwrap because Ecto.Type.cast/2
        |> Result.unwrap()
    }
  end

  @spec get_message_from_decoded_line(map()) :: Result.t(String.t, :not_found)
  defp get_message_from_decoded_line(decoded) do
    decoded["line"]["message"]
    |> case do
      nil -> error(:not_found)
      result -> ok(result)
    end
  end

  @spec get_msisdn(String.t) :: Result.t(String.t, MsisdnNotFound)
  defp get_msisdn(message) do
    Regex.run(~r/msisdn=(\d+)\s/, message)
    |> case do
      nil -> error(MsisdnNotFound)
      [_, msisdn] -> ok(msisdn)
    end
  end

  @spec get_reason(String.t) :: Result.t(String.t, ReasonNotFound)
  defp get_reason(message) do
    Regex.run(~r/reason: :(\w+)$/, message)
    |> case do
      nil -> error(ReasonNotFound)
      [_, reason] -> ok(reason)
    end
  end

  @spec get_timestamp(String.t) :: Result.t(String.t, TimestampNotFound)
  defp get_timestamp(message) do
    Regex.named_captures(~r/^(?<date>\$?\d+-\d+-\d+) (?<time>\d+:\d+:\d+.\d+)/, message)
    |> Option.to_option()
    |> MonEx.map(fn capture ->
        "#{capture["date"]}T#{capture["time"]}Z"
      end)
    |> Option.ok_or_else(TimestampNotFound)
  end
end
/home/svv/dvp/Elixir/json_to_psql/lib/failed_offers/decoder.ex
```

**Comment by rrrene** [comment]
This is part of `1.7.2-rc.3` :+1: (ouch, sorry for the late reply)

**Comment by rrrene** [comment]
This is part of Credo `1.7.2`. :+1:
