### ISSUE TITLE
[Bug]credo compilation failure

### ISSUE THREAD

**Issue by apoorv-2204** [rrrene/credo#1061]
```
== Compilation error in file lib/credo/check/consistency/exception_names.ex ==
** (RuntimeError) Could not find key `id` in [:base_priority, :category, :elixir_version, :exit_status, :explanations, :param_defaults, :run_on_all, :tags]
    (credo 1.6.7) lib/credo/check.ex:189: anonymous fn/1 in Credo.Check."MACRO-__using__"/2
    (elixir 1.14.1) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (credo 1.6.7) expanding macro: Credo.Check.__using__/1
    lib/credo/check/consistency/exception_names.ex:2: Credo.Check.Consistency.ExceptionNames (module)
    (elixir 1.14.1) expanding macro: Kernel.use/2
    lib/credo/check/consistency/exception_names.ex:2: Credo.Check.Consistency.ExceptionNames (module)
[Warn  - 21:24:36] could not compile dependency :credo, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile credo", update it with "mix deps.update credo" or clean it with "mix deps.clean credo"
`

**Comment by rrrene** [comment]
@apoorv-2204 I am not sure what is going on here.

Please fill out the info that was requested in the issue template. Ignoring the issue template does not help when reporting a bug.

**Comment by rrrene** [comment]
Closing this as it should have been foyed in the meantime. 

Please re-open if it is still a problem 👍
