### ISSUE TITLE
Config - Excluding directory results in error

### ISSUE THREAD

**Issue by alkamin** [rrrene/credo#11]
adding any directory to the `excluded` array, eg. `lib/mix/tasks/`,  in `.credo.exs`,  causes this error:

```
(elixir) lib/regex.ex:158: Regex.match?("./lib/mix/tasks", "lib/test_api.ex")                    
(elixir) lib/enum.ex:2279: Enum.do_any?/2                                                          
(elixir) lib/enum.ex:1476: anonymous fn/3 in Enum.reject/2                                         
(elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3                                     
(elixir) lib/enum.ex:1476: Enum.reject/2                                                           
lib/credo/sources.ex:7: Credo.Sources.find/1                                                       
lib/credo/cli/command/list.ex:26: anonymous fn/1 in Credo.CLI.Command.List.load_and_validate_source_files/1                                                                                           
(stdlib) timer.erl:166: :timer.tc/1 
```

Great tool! Thanks!

**Comment by rrrene** [comment]
`v0.1.7` contains the fix! :shipit:

**Comment by alkamin** [comment]
Thanks, works great
