### ISSUE TITLE
FunctionClauseError when running `mix credo.gen.check` and `mix credo.gen.config` 

### ISSUE THREAD

**Issue by remiprev** [rrrene/credo#110]
I just upgraded to `credo-0.4.0` and I get an error when I run the two new `mix` commands:

```bash
% mix credo.gen.check
** (FunctionClauseError) no function clause matching in Credo.CLI.command_for/1
    lib/credo/cli.ex:72: Credo.CLI.command_for(Credo.CLI.Command.GenCheck)
    lib/credo/cli.ex:134: Credo.CLI.command_name_dir_config/3
    lib/credo/cli.ex:82: Credo.CLI.run/1
    lib/credo/cli.ex:58: Credo.CLI.main/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

% mix credo.gen.config
** (FunctionClauseError) no function clause matching in Credo.CLI.command_for/1
    lib/credo/cli.ex:72: Credo.CLI.command_for(Credo.CLI.Command.GenConfig)
    lib/credo/cli.ex:134: Credo.CLI.command_name_dir_config/3
    lib/credo/cli.ex:82: Credo.CLI.run/1
    lib/credo/cli.ex:58: Credo.CLI.main/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Is there something I’m missing?

**Comment by rrrene** [comment]
Embarrasing. Please try Credo `v0.4.1`! :cold_sweat:

**Comment by remiprev** [comment]
Yep, all working now! I’m going to close the issue. Thanks! 😄
