### ISSUE TITLE
missing spec on unquoted function raise error

### ISSUE THREAD

**Issue by aleagnelli** [rrrene/credo#1114]
### Environment

* Credo version (`mix credo -v`): 1.7.4
* Erlang/Elixir version (`elixir -v`): OTP 26.2.1, elixir 1.16.0 and 1.16.1
* Operating system: fedora 39, ubuntu 22.04

### What were you trying to do?

```elixir
defmodule SpecIssue do
  function_name = :do_something

  def unquote(function_name)() do
    :ok
  end
end
```

### Expected outcome

correctly reporting missing spec

### Actual outcome

```
Checking 22 source files ...
Error while running Elixir.Credo.Check.Readability.Specs on lib/spec_issue.ex

10:12:12.077 [error] Task #PID<0.221.0> started from #PID<0.204.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 4, column: 7], [{:function_name, [line: 4, column: 15], nil}]} of type Tuple
    (elixir 1.16.0) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.16.0) lib/string/chars.ex:22: String.Chars.to_string/1
    (credo 1.7.4) lib/credo/check.ex:722: Credo.Check.format_issue/5
    (credo 1.7.4) lib/credo/check/readability/specs.ex:104: Credo.Check.Readability.Specs.traverse/4
    (elixir 1.16.0) lib/macro.ex:637: anonymous fn/4 in Macro.do_traverse_args/4
    (stdlib 5.2) lists.erl:1706: :lists.mapfoldl_1/3
    (stdlib 5.2) lists.erl:1707: :lists.mapfoldl_1/3
    (elixir 1.16.0) lib/macro.ex:602: Macro.do_traverse/4
Function: &:erlang.apply/2
    Args: [#Function<0.66951469/1 in Credo.Check.Readability.Specs.do_run_on_all_source_files/3>, [%SourceFile<lib/spec_issue.ex>]]
** (EXIT from #PID<0.99.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 4, column: 7], [{:function_name, [line: 4, column: 15], nil}]} of type Tuple
        (elixir 1.16.0) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir 1.16.0) lib/string/chars.ex:22: String.Chars.to_string/1
        (credo 1.7.4) lib/credo/check.ex:722: Credo.Check.format_issue/5
        (credo 1.7.4) lib/credo/check/readability/specs.ex:104: Credo.Check.Readability.Specs.traverse/4
        (elixir 1.16.0) lib/macro.ex:637: anonymous fn/4 in Macro.do_traverse_args/4
        (stdlib 5.2) lists.erl:1706: :lists.mapfoldl_1/3
        (stdlib 5.2) lists.erl:1707: :lists.mapfoldl_1/3
        (elixir 1.16.0) lib/macro.ex:602: Macro.do_traverse/4

```

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by aleagnelli** [comment]
> Thanks for reporting this 😀 It is now fixed on `master`.
> 
> You can try this by setting the Credo dep to
> 
> ```elixir
> {:credo, github: "rrrene/credo"}
> ```
> 
> Please report back if your issue is solved! 👍

I tried right now, the fix is working. Thank you! :smile:

**Comment by rrrene** [comment]
This is live in `v1.7.5`.
