### ISSUE TITLE
Compilation failure on clean install of 1.7.11

### ISSUE THREAD

**Issue by s3cur3** [rrrene/credo#1171]
### Environment

* Credo version (`mix credo -v`): 1.7.11
* Erlang/Elixir version (`elixir -v`): 1.17.3
* Operating system: macOS Sequoia 15.2 (24C101)

### What were you trying to do?

Install credo and compile it.

1. Add `{:credo, "~> 1.7", only: [:dev, :test], runtime: false},` to my `mix.exs` deps
2. `mix deps.get`
3. `mix credo`

### Expected outcome

Credo compiles and runs using the default config

### Actual outcome

I get the following compilation failure:

```
==> credo
Compiling 108 files (.ex)

== Compilation error in file lib/credo/check.ex ==
** (Code.LoadError) could not load /Users/tyler/jump/api/deps/credo/.credo.exs. Reason: enoent
    (elixir 1.17.3) lib/code.ex:2158: Code.find_file!/2
    (elixir 1.17.3) lib/code.ex:1430: Code.eval_file/2
    lib/credo/check.ex:198: (module)
could not compile dependency :credo, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile credo --force", update it with "mix deps.update credo" or clean it with "mix deps.clean credo"
```

I confirm that my `deps/credo/` directory does not have a `.credo.exs` file, nor any other file with a `.` prefix.

If I back down to Credo v1.7.10, the `.credo.exs` file appears and I'm able to compile and run. Likewise, if I generate a config on 1.7.10 and then upgrade to 1.7.11, `mix credo` works.

**Comment by rrrene** [comment]
That is definitely odd. I can not reproduce this with my sample project on Linux:

```bash
(master ?M) ~/projects/credo_sample_project$ rm -fr deps/
rrrene@hawkins 
(master ?M) ~/projects/credo_sample_project$ mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.032s
Because the lock depends on credo 1.6.1 which depends on file_system ~> 0.2.8, the lock requires file_system ~> 0.2.8.
And because "the lock" specifies file_system 1.0.0, no version of the lock is allowed.
So, because your app depends on the lock, version solving failed.
** (Mix) Hex dependency resolution failed
rrrene@hawkins 
(master ?M) ~/projects/credo_sample_project$ mix deps.update credo
Resolving Hex dependencies...
Resolution completed in 0.023s
Unchanged:
  bunt 1.0.0
Upgraded:
  credo 1.6.1 => 1.7.11
  file_system 1.0.0 => 1.0.1
  jason 1.4.1 => 1.4.4
* Getting credo (Hex package)
* Getting file_system (Hex package)
* Getting jason (Hex package)
rrrene@hawkins 
(master ?M) ~/projects/credo_sample_project$ mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.032s
Unchanged:
  bunt 1.0.0
  credo 1.7.11
  file_system 1.0.1
  jason 1.4.4
* Getting bunt (Hex package)
rrrene@hawkins 
(master ?M) ~/projects/credo_sample_project$ 
rrrene@hawkins 
(master ?M) ~/projects/credo_sample_project$ mix credo
==> file_system
Compiling 7 files (.ex)
Generated file_system app
==> bunt
Compiling 2 files (.ex)
Generated bunt app
==> jason
Compiling 10 files (.ex)
Generated jason app
==> credo
Compiling 251 files (.ex)
Generated credo app
Checking 8 source files ...

  Code Readability                                                                                                                                                        
┃ 
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/my_project/checks/my_consistency_check.ex:1:11 #(MyProject.Checks.SpaceInParentheses)
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/my_project/checks/reject_module_attributes.ex:1:11 #(MyProject.Checks.RejectModuleAttributes)
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/example_app.ex:1:11 #(ExampleApp)

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 0.04 seconds (0.01s to load, 0.03s running 55 checks on 8 files)
32 mods/funs, found 3 code readability issues.

Showing priority issues: ↑ ↗ →  (use `mix credo explain` to explain issues, `mix credo --help` for options).
rrrene@hawkins 
(master ?M) ~/projects/credo_sample_project$ ls -al deps/credo/
total 116
drwxrwxr-x 3 rrrene rrrene  4096 Jan  1 10:49 .
drwxrwxr-x 6 rrrene rrrene  4096 Jan  1 10:49 ..
-rw-rw-r-- 1 rrrene rrrene 45541 Jan  1 10:49 CHANGELOG.md
-rw-rw-r-- 1 rrrene rrrene  8873 Jan  1 10:49 .credo.exs
-rw-rw-r-- 1 rrrene rrrene     0 Jan  1 10:49 .fetch
-rw-rw-r-- 1 rrrene rrrene   262 Jan  1 10:49 .hex
-rw-rw-r-- 1 rrrene rrrene 15525 Jan  1 10:49 hex_metadata.config
drwxrwxr-x 4 rrrene rrrene  4096 Jan  1 10:49 lib
-rw-rw-r-- 1 rrrene rrrene  1063 Jan  1 10:49 LICENSE
-rw-rw-r-- 1 rrrene rrrene  4305 Jan  1 10:49 mix.exs
-rw-rw-r-- 1 rrrene rrrene  2844 Jan  1 10:49 README.md
-rw-rw-r-- 1 rrrene rrrene  1843 Jan  1 10:49 .template.check.ex
-rw-rw-r-- 1 rrrene rrrene  2668 Jan  1 10:49 .template.debug.html

```

Open for any ideas/suggestions :-/

**Comment by s3cur3** [comment]
Hm... this is super weird. I went back, removed `deps/credo/` and my own Credo config entirely, and reran `mix deps.get` to grab 1.7.11, and this time I _did_ get the three `.`-prefixed files. I'm gonna say this isn't a Credo issue at all. Sorry to waste your time, @rrrene! 🤦‍♂️
