### ISSUE TITLE
Bug in NameRedeclarationByDef

### ISSUE THREAD

**Issue by andrewtimberlake** [rrrene/credo#191]
When running Credo on a specific file I get the following error

```
** (EXIT from #PID<0.70.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:., [line: 165], [{:__aliases__, [counter: 0, line: 165], [:Type]}, :cost]}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
        lib/credo/check/warning/name_redeclaration_by_def.ex:114: Credo.Check.Warning.NameRedeclarationByDef.find_issue/4
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        lib/credo/check/warning/name_redeclaration_by_def.ex:73: Credo.Check.Warning.NameRedeclarationByDef.mod_traverse/5
        (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
```

I have tried to figure it out but I’m not exactly sure where the problem is.
I have a module `AccountTransaction.Type` which implements a macro `cost` which returns a constant `1`
The file that the check raises the above error I have code similar to:

``` elixir
require AccountTransaction.Type
alias AccountTransaction.Type

def my_func(%{type_id: type} = data) when type != Type.cost do
end
```

There are no methods in the failing module that are named `type` or `cost`
If I disable NameRedeclarationByDef I can successfully run Credo against the whole project without error.

**Comment by sstern6** [comment]
@andrewtimberlake I was unable to reproduce the bug.  I pasted the code you provided into a file locally, and ran `mix credo filename.ex` with `{Credo.Check.Warning.NameRedeclarationByDef}` enabled in my config file.

Can you please paste in your full file, config, and version of credo you are currently using?

Thank you

cc @rrrene

**Comment by rrrene** [comment]
@andrewtimberlake Thx for reporting this. 👍  
@sstern6 Thx for jumping in! 😬 

I am currently on vacation (and a spotty wifi). Will be back next weekend!

**Comment by SamuelMV** [comment]
Hello, I think we have the same issue (with Credo 0.4.13):

```
** (EXIT from #PID<0.70.0>) an exception was raised:
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:., [line: 8], [{:__aliases__, [counter: 0, line: 8], [:SEPAConst]}, :code_seq_destination_bic_1]}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
        lib/credo/check/warning/name_redeclaration_by_def.ex:114: Credo.Check.Warning.NameRedeclarationByDef.find_issue/4
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        lib/credo/check/warning/name_redeclaration_by_def.ex:73: Credo.Check.Warning.NameRedeclarationByDef.mod_traverse/5
        (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
...
```

We started having the same error in Credo when we added a module with constants (using this [gist](https://gist.github.com/smpallen99/9995893) that uses macros):

```
defmodule SEPA.Constants do
  use Constants
  constant code_seq_destination_bic_1, "00000100"
end
```

If you need more information, please, tell me.

Thank you

**Comment by sstern6** [comment]
Thanks for the additional information @SamuelMV.  Will look into it and let you know if i have any more questions.  I think i might have an idea of what is going on, but not entirely sure 😄 !

**Comment by sstern6** [comment]
@SamuelMV are you still having this issue with the most recent version of credo?

**Comment by andrewtimberlake** [comment]
The bug is still present in Credo 0.5.1
I have managed to reproduce it here: https://github.com/andrewtimberlake/credo_test

**Comment by sstern6** [comment]
Thanks @andrewtimberlake will look more into this

**Comment by rrrene** [comment]
Found it! I plan to release a new version this weekend :+1:

**Comment by SamuelMV** [comment]
Sorry about the delay. I just tried with credo 0.5.1 and is still present. This is the output if you need it:

```
** (EXIT from #PID<0.70.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:., [line: 8], [{:__aliases__, [counter: 0, line: 8], [:SEPAConst]}, :code_seq_gateway_bic]}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
        lib/credo/check/warning/name_redeclaration_by_def.ex:114: Credo.Check.Warning.NameRedeclarationByDef.find_issue/4
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        lib/credo/check/warning/name_redeclaration_by_def.ex:73: Credo.Check.Warning.NameRedeclarationByDef.mod_traverse/5
        (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3

23:45:13.347 [error] Task #PID<0.203.0> started from #PID<0.70.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:., [line: 8], [{:__aliases__, [counter: 0, line: 8], [:SEPAConst]}, :code_seq_gateway_bic]}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    lib/credo/check/warning/name_redeclaration_by_def.ex:114: Credo.Check.Warning.NameRedeclarationByDef.find_issue/4
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    lib/credo/check/warning/name_redeclaration_by_def.ex:73: Credo.Check.Warning.NameRedeclarationByDef.mod_traverse/5
    (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
Function: #Function<13.121687013/0 in Credo.Check.Runner.run/2>
    Args: []

23:45:13.354 [error] GenServer Credo.Supervisor terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:., [line: 8], [{:__aliases__, [counter: 0, line: 8], [:SEPAConst]}, :code_seq_gateway_bic]}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    lib/credo/check/warning/name_redeclaration_by_def.ex:114: Credo.Check.Warning.NameRedeclarationByDef.find_issue/4
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    lib/credo/check/warning/name_redeclaration_by_def.ex:73: Credo.Check.Warning.NameRedeclarationByDef.mod_traverse/5
    (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
Last message: {:EXIT, #PID<0.70.0>, {%Protocol.UndefinedError{description: "", protocol: String.Chars, value: {:., [line: 8], [{:__aliases__, [counter: 0, line: 8], [:SEPAConst]}, :code_seq_gateway_bic]}}, [{String.Chars, :impl_for!, 1, [file: 'lib/string/chars.ex', line: 3]}, {String.Chars, :to_string, 1, [file: 'lib/string/chars.ex', line: 17]}, {Credo.Check.Warning.NameRedeclarationByDef, :find_issue, 4, [file: 'lib/credo/check/warning/name_redeclaration_by_def.ex', line: 114]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1184]}, {Credo.Check.Warning.NameRedeclarationByDef, :mod_traverse, 5, [file: 'lib/credo/check/warning/name_redeclaration_by_def.ex', line: 73]}, {Macro, :"-do_traverse_args/4-fun-0-", 4, [file: 'lib/macro.ex', line: 296]}, {Enum, :"-map_reduce/3-lists^mapfoldl/2-0-", 3, [file: 'lib/enum.ex', line: 1247]}, {Enum, :"-map_reduce/3-lists^mapfoldl/2-0-", 3, [file: 'lib/enum.ex', line: 1247]}]}}
State: {:state, {:local, Credo.Supervisor}, :one_for_one, [{:child, #PID<0.162.0>, Credo.Service.SourceFileIssues, {Credo.Service.SourceFileIssues, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileIssues]}, {:child, #PID<0.161.0>, Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {:child, #PID<0.160.0>, Credo.Service.SourceFileCodeOnly, {Credo.Service.SourceFileCodeOnly, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileCodeOnly]}, {:child, #PID<0.159.0>, Credo.Service.SourceFileWithoutStringAndSigils, {Credo.Service.SourceFileWithoutStringAndSigils, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileWithoutStringAndSigils]}], :undefined, 3, 5, [], 0, Supervisor.Default, {:ok, {{:one_for_one, 3, 5}, [{Credo.Service.SourceFileWithoutStringAndSigils, {Credo.Service.SourceFileWithoutStringAndSigils, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileWithoutStringAndSigils]}, {Credo.Service.SourceFileCodeOnly, {Credo.Service.SourceFileCodeOnly, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileCodeOnly]}, {Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {Credo.Service.SourceFileIssues, {Credo.Service.SourceFileIssues, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileIssues]}]}}}
```

Thank you again :D

**Comment by rrrene** [comment]
@SamuelMV Correct. We just fixed the bug. A new version will be released soon! :+1: (see my previous comment)
