### ISSUE TITLE
Bug in regex

### ISSUE THREAD

**Issue by andrewtimberlake** [rrrene/credo#201]
Running credo (0.4.13, Elixir 1.3.3) against [https://github.com/andrewtimberlake/elixir-pdf] I get the following error,

```
==> credo
Compiling 120 files (.ex)
Generated credo app
Checking 19 source files ...
** (EXIT from #PID<0.70.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Regex.match?/2
        (elixir) lib/regex.ex:159: Regex.match?(~r/(\.\w+Controller|\.Endpoint|\.Mixfile|\.Repo|\.Router|\.\w+Socket|\w+Test|\.\w+View)$/, nil)
        (elixir) lib/enum.ex:2511: Enum.do_any?/2
        lib/credo/check/readability/module_doc.ex:42: Credo.Check.Readability.ModuleDoc.traverse/4
        (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:262: Macro.do_traverse/4
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3

16:31:52.311 [error] Task #PID<0.906.0> started from #PID<0.70.0> terminating
** (FunctionClauseError) no function clause matching in Regex.match?/2
    (elixir) lib/regex.ex:159: Regex.match?(~r/(\.\w+Controller|\.Endpoint|\.Mixfile|\.Repo|\.Router|\.\w+Socket|\w+Test|\.\w+View)$/, nil)
    (elixir) lib/enum.ex:2511: Enum.do_any?/2
    lib/credo/check/readability/module_doc.ex:42: Credo.Check.Readability.ModuleDoc.traverse/4
    (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:262: Macro.do_traverse/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
Function: #Function<13.121687013/0 in Credo.Check.Runner.run/2>
    Args: []

16:31:52.312 [error] GenServer Credo.Supervisor terminating
** (FunctionClauseError) no function clause matching in Regex.match?/2
    (elixir) lib/regex.ex:159: Regex.match?(~r/(\.\w+Controller|\.Endpoint|\.Mixfile|\.Repo|\.Router|\.\w+Socket|\w+Test|\.\w+View)$/, nil)
    (elixir) lib/enum.ex:2511: Enum.do_any?/2
    lib/credo/check/readability/module_doc.ex:42: Credo.Check.Readability.ModuleDoc.traverse/4
    (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:262: Macro.do_traverse/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
Last message: {:EXIT, #PID<0.70.0>, {:function_clause, [{Regex, :match?, [~r/(\.\w+Controller|\.Endpoint|\.Mixfile|\.Repo|\.Router|\.\w+Socket|\w+Test|\.\w+View)$/, nil], [file: 'lib/regex.ex', line: 159]}, {Enum, :do_any?, 2, [file: 'lib/enum.ex', line: 2511]}, {Credo.Check.Readability.ModuleDoc, :traverse, 4, [file: 'lib/credo/check/readability/module_doc.ex', line: 42]}, {Macro, :"-do_traverse_args/4-fun-0-", 4, [file: 'lib/macro.ex', line: 296]}, {Enum, :"-map_reduce/3-lists^mapfoldl/2-0-", 3, [file: 'lib/enum.ex', line: 1247]}, {Enum, :"-map_reduce/3-lists^mapfoldl/2-0-", 3, [file: 'lib/enum.ex', line: 1247]}, {Macro, :do_traverse, 4, [file: 'lib/macro.ex', line: 262]}, {Enum, :"-map_reduce/3-lists^mapfoldl/2-0-", 3, [file: 'lib/enum.ex', line: 1247]}]}}
State: {:state, {:local, Credo.Supervisor}, :one_for_one, [{:child, #PID<0.865.0>, Credo.Service.SourceFileIssues, {Credo.Service.SourceFileIssues, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileIssues]}, {:child, #PID<0.864.0>, Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {:child, #PID<0.863.0>, Credo.Service.SourceFileCodeOnly, {Credo.Service.SourceFileCodeOnly, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileCodeOnly]}, {:child, #PID<0.862.0>, Credo.Service.SourceFileWithoutStringAndSigils, {Credo.Service.SourceFileWithoutStringAndSigils, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileWithoutStringAndSigils]}], :undefined, 3, 5, [], 0, Supervisor.Default, {:ok, {{:one_for_one, 3, 5}, [{Credo.Service.SourceFileWithoutStringAndSigils, {Credo.Service.SourceFileWithoutStringAndSigils, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileWithoutStringAndSigils]}, {Credo.Service.SourceFileCodeOnly, {Credo.Service.SourceFileCodeOnly, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileCodeOnly]}, {Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {Credo.Service.SourceFileIssues, {Credo.Service.SourceFileIssues, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileIssues]}]}}}
```

**Comment by rrrene** [comment]
Thx for reporting!
