### ISSUE TITLE
Cannot run credo mix task

### ISSUE THREAD

**Issue by wafcio** [rrrene/credo#212]
### Precheck

I have just updated hex to 0.14.0 version (I don't remember which one I had previously). I am not able to run mix task successfully.

### Environment

* Credo version (`mix credo -v`): 0.4.13
* Erlang/Elixir version (`elixir -v`):
```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.2
```
* Operating system: macOS Sierra 10.12

### What are you trying to do?

I try to run ```$ mix credo```

### Expected outcome

Run code analysis

### Actual outcome

```
** (UndefinedFunctionError) function Hex.Utils.ensure_registry!/0 is undefined or private
    (hex) Hex.Utils.ensure_registry!()
    lib/credo/check_for_updates.ex:4: Credo.CheckForUpdates.run/0
    lib/credo/cli.ex:92: Credo.CLI.run/1
    lib/credo/cli.ex:58: Credo.CLI.main/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

**Comment by wafcio** [comment]
I have updated credo to 0.5.1 and problem disappeared.
