### ISSUE TITLE
Credo crashes with httpc error when starting

### ISSUE THREAD

**Issue by Nicd** [rrrene/credo#223]
### Environment

* Credo version (`mix credo -v`): Unable to run as credo crashes but latest at the time of writing (cloned from git repo).
* Erlang/Elixir version (`elixir -v`): Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace], Elixir 1.3.4
* Operating system: Mac OS X 10.11.6

### What where you trying to do?

Run `mix credo`.

### Expected outcome

It runs.

### Actual outcome

```
$ mix credo
** (exit) exited in: :gen_server.call(:httpc_manager, {:request, {:request, :undefined, #PID<0.70.0>, 0, :https, {'hex.pm', 443}, '/api/packages/credo', [], :get, {:http_request_h, :undefined, 'keep-alive', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, 'application/vnd.hex+erlang', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, 'hex.pm', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], 'Credo/0.5.2 (Elixir/1.3.4) (OTP/19)', :undefined, :undefined, :undefined, '0', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, ...}, {[], []}, {:http_options, 'HTTP/1.1', :infinity, true, {:essl, []}, :undefined, false, :infinity, false}, 'https://hex.pm/api/packages/credo', [], :none, [], 1478865591843, :undefined, :undefined, false}}, :infinity)
    ** (EXIT) no process
    (stdlib) gen_server.erl:212: :gen_server.call/3
    httpc.erl:574: :httpc.handle_request/9
    lib/credo/check_for_updates.ex:66: Credo.CheckForUpdates.fetch/1
    lib/credo/check_for_updates.ex:59: Credo.CheckForUpdates.fetch_all_hex_versions/1
    lib/credo/check_for_updates.ex:4: Credo.CheckForUpdates.run/0
    lib/credo/cli.ex:92: Credo.CLI.run/1
    lib/credo/cli.ex:58: Credo.CLI.main/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
```

**Comment by rrrene** [comment]
Could you clone `master` and try again? I added `:inets` to the list of applicatons.

**Comment by Nicd** [comment]
Nope, still the same error.

**Comment by rrrene** [comment]
@sstern6 Can you reproduce this?

I will try to reproduce it at home on the weekend, but I am wondering if this is OS X specific.

**Comment by sstern6** [comment]
@rrrene i cant seem to reproduce..

@Nicd what version of mix do you currently have installed?

**Comment by Nicd** [comment]
I have Mix 1.3.4

**Comment by sstern6** [comment]
Can you please try uninstalling credo and reinstalling, im having trouble reproducing on my mac but will keep digging.

**Comment by Nicd** [comment]
I've uninstalled and reinstalled the master (after instructed), manually `rm -rf'd` the archive from hex and installed it again after a clean build.

**Comment by sstern6** [comment]
ok let me continue looking into it

**Comment by sstern6** [comment]
@Nicd are you still having this issue?

**Comment by Nicd** [comment]
Yes, I pulled the latest master, `rm -rf ~/.mix/archives/credo* && rm -rf _build && mix clean && mix deps.clean && mix deps.get && mix archive.build && mix archive.install`. Still the same issue.

**Comment by brienw** [comment]
I can reproduce this as well. here's my wall of output:

```
open_source/credo git:(master) mix deps.get
Running dependency resolution
* Getting bunt (Hex package)
  Checking package (https://repo.hex.pm/tarballs/bunt-0.1.6.tar)
  Fetched package
* Getting inch_ex (Hex package)
  Checking package (https://repo.hex.pm/tarballs/inch_ex-0.5.3.tar)
  Fetched package
* Getting coverex (Hex package)
  Checking package (https://repo.hex.pm/tarballs/coverex-1.4.9.tar)
  Fetched package
* Getting httpoison (Hex package)
  Checking package (https://repo.hex.pm/tarballs/httpoison-0.9.0.tar)
  Fetched package
* Getting poison (Hex package)
  Checking package (https://repo.hex.pm/tarballs/poison-2.2.0.tar)
  Fetched package
* Getting hackney (Hex package)
  Checking package (https://repo.hex.pm/tarballs/hackney-1.6.0.tar)
  Fetched package
* Getting certifi (Hex package)
  Checking package (https://repo.hex.pm/tarballs/certifi-0.4.0.tar)
  Fetched package
* Getting idna (Hex package)
  Checking package (https://repo.hex.pm/tarballs/idna-1.2.0.tar)
  Fetched package
* Getting metrics (Hex package)
  Checking package (https://repo.hex.pm/tarballs/metrics-1.0.1.tar)
  Fetched package
* Getting mimerl (Hex package)
  Checking package (https://repo.hex.pm/tarballs/mimerl-1.0.2.tar)
  Fetched package
* Getting ssl_verify_fun (Hex package)
  Checking package (https://repo.hex.pm/tarballs/ssl_verify_fun-1.1.0.tar)
  Fetched package
open_source/credo git:(master) ○ mix archive.build
==> bunt
Compiling 2 files (.ex)
warning: redefining module Bunt (current version loaded from /Users/brien/.mix/archives/bunt-0.1.6/bunt-0.1.6/ebin/Elixir.Bunt.beam)
  lib/bunt.ex:1

warning: redefining module Bunt.ANSI.Sequence (current version loaded from /Users/brien/.mix/archives/bunt-0.1.6/bunt-0.1.6/ebin/Elixir.Bunt.ANSI.Sequence.beam)
  lib/bunt_ansi.ex:1

warning: redefining module Bunt.ANSI (current version loaded from /Users/brien/.mix/archives/bunt-0.1.6/bunt-0.1.6/ebin/Elixir.Bunt.ANSI.beam)
  lib/bunt_ansi.ex:29

Generated bunt app
==> poison
Compiling 4 files (.ex)
Generated poison app
==> inch_ex
Compiling 15 files (.ex)
Generated inch_ex app
==> credo
Compiling 122 files (.ex)
Generated credo app
Generated archive "credo-0.5.2.ez" with MIX_ENV=dev
open_source/credo git:(master) ○ mix archive.install
Are you sure you want to install archive "credo-0.5.2.ez"? [Yn] y
* creating /Users/brien/.mix/archives/credo-0.5.2
open_source/credo git:(master) ○ mix credo
** (exit) exited in: :gen_server.call(:httpc_manager, {:request, {:request, :undefined, #PID<0.70.0>, 0, :https, {'hex.pm', 443}, '/api/packages/credo', [], :get, {:http_request_h, :undefined, 'keep-alive', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, 'application/vnd.hex+erlang', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, 'hex.pm', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], 'Credo/0.5.2 (Elixir/1.3.4) (OTP/19)', :undefined, :undefined, :undefined, '0', :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, ...}, {[], []}, {:http_options, 'HTTP/1.1', :infinity, true, {:essl, []}, :undefined, false, :infinity, false}, 'https://hex.pm/api/packages/credo', [], :none, [], 1479254169103, :undefined, :undefined, false}}, :infinity)
    ** (EXIT) no process
    (stdlib) gen_server.erl:212: :gen_server.call/3
    httpc.erl:574: :httpc.handle_request/9
    lib/credo/check_for_updates.ex:66: Credo.CheckForUpdates.fetch/1
    lib/credo/check_for_updates.ex:59: Credo.CheckForUpdates.fetch_all_hex_versions/1
    lib/credo/check_for_updates.ex:4: Credo.CheckForUpdates.run/0
    lib/credo/cli.ex:92: Credo.CLI.run/1
    lib/credo/cli.ex:58: Credo.CLI.main/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3

open_source/credo git:(master) ○ elixir -v
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.4
open_source/credo git:(master) ○ sw_vers -productVersion
10.12.1
open_source/credo git:(master) ○ mix -v
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Mix 1.3.4
```

**Comment by brienw** [comment]
I've narrowed it down to this commit 47562b0a021e1fbc36b399aefabf2bdf537d7186

```
open_source/credo git:(master) ○ git reset --hard 0b797184f371ee190c29fbd5f0d406549d259c08
HEAD is now at 0b79718 Bump version to 0.5.0
open_source/credo git:(master:29) rm -rf ~/.mix/archives/credo* && rm -rf _build && mix clean && mix deps.clean --all && mix deps.get && mix archive.build && mix archive.install
< snip >
open_source/credo git:(master:29) ○ mix credo
A new Credo version is available (0.5.2), please update with `mix deps.update credo`
Checking 120 source files (this might take a while) ...
```

then if i roll it forward to the version 0.5.1 commit i get:

```
open_source/credo git:(master:29) ○ git reset --hard 07e7eb4ee8bd7d5d95fc9fb5e1e83ab31e820f57
HEAD is now at 07e7eb4 Bump version to 0.5.1
open_source/credo git:(master:27) rm -rf ~/.mix/archives/credo* && rm -rf _build && mix clean && mix deps.clean --all && mix deps.get && mix archive.build && mix archive.install
< snip >
open_source/credo git:(master:27) ○ mix credo
** (exit) exited in: :gen_server.call(:httpc_manager...
```

**Comment by rrrene** [comment]
@brienw Thx for checking! Unfortunately, this is not surprising since that is the commit where I started using `:httpc` (in favor of using undocumented, private Hex APIs, which was a terrible idea in the first place).

You should be able to prevent Credo from crashing by using the `check_for_updates: false` in your config.

**Comment by sstern6** [comment]
@rrrene was there a reason you decided to abandon the Hex module you were using before that commit out of curiosity?

**Comment by rrrene** [comment]
@sstern6 Using undocumented APIs from another project (Hex in this case) is never a good idea because

a) the owner did not intend for you to use undocumented functions/behaviour and
b) all projects depending on Credo broke when they updated the seemingly unrelated Hex. 

That was really bad (in my opinion), because contrary to Ruby, Python or JS, it's not that some part of your project broke or Credo would not run on your CI. No, in this scenario, your project did no longer compile. At all. 

I am glad that Eric and José helped remedy the situation, when that was pretty clearly my fault and a very bad decision to begin with. So, yeah, don't use undocumented stuff or you might find yourself in an embarassing situation like this. :neckbeard:

**Comment by Nicd** [comment]
Can confirm this fixes the issue! 👍

**Comment by sstern6** [comment]
@rrrene thanks for the explanation.
