### ISSUE TITLE
mix archive.build => KeyError, key :strict not found in %Credo.Config{ ... } 

### ISSUE THREAD

**Issue by Dangeranger** [rrrene/credo#274]
### Environment

* Credo version (`mix credo -v`): **0.6.0 (pre)**, commit **7be7090fa4afb8f9d113b351d1b3858c974453ec**
* Erlang/Elixir version (`elixir -v`): `Elixir 1.3.2`
* Rebar Version: `rebar 2.6.0 17 20150627_044508`
* Operating system:
```
ProductName:    Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F2009
```
### What were you trying to do?

- Build Credo from latest source according to [README#Standalone](https://github.com/rrrene/credo#using-credo-as-stand-alone)
Steps:
```
git clone git@github.com:rrrene/credo.git credo
mix deps.get
mix archive.build
```

### Expected outcome

Expeced an archive to be build for use in `mix archive.install`

### Actual outcome

Resulted in error:
```elixir
== Compilation error on file lib/credo/config.ex ==
** (KeyError) key :strict not found in: %Credo.Config{ ...truncated... }
   lib/credo/config.ex:7: anonymous fn/2 in Credo.Config.__struct__/1
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding struct: Credo.Config.__struct__/1
    lib/credo/config.ex:146: Credo.Config.from_data/3
```

Full error below:
```elixir
== Compilation error on file lib/credo/config.ex ==
** (KeyError) key :strict not found in: %Credo.Config{all: false, check_for_updates: {:case, [line: 147], [{{:., [line: 147], [Access, :get]}, [line: 147], [{:data, [line: 147], nil}, :check_for_updates]}, [do: [{:->, [line: 147], [[{:when, [line: 147], [{:x, [counter: -576460752303414196, line: 147], Kernel}, {{:., [line: 147], [:erlang, :or]}, [line: 147], [{{:., [line: 147], [:erlang, :"=:="]}, [line: 147], [{:x, [counter: -576460752303414196, line: 147], Kernel}, nil]}, {{:., [line: 147], [:erlang, :"=:="]}, [line: 147], [{:x, [counter: -576460752303414196, line: 147], Kernel}, false]}]}]}], false]}, {:->, [line: 147], [[{:x, [counter: -576460752303414196, line: 147], Kernel}], {:x, [counter: -576460752303414196, line: 147], Kernel}]}]]]}, checks: {:checks_from_data, [line: 150], [{:data, [line: 150], nil}]}, crash_on_error: true, files: {:files_from_data, [line: 149], [{:data, [line: 149], nil}, {:dir, [line: 149], nil}]}, format: nil, help: false, ignore_checks: nil, lint_attribute_map: %{}, match_checks: nil, min_priority: 0, read_from_stdin: false, requires: {:case, [line: 148], [{{:., [line: 148], [Access, :get]}, [line: 148], [{:data, [line: 148], nil}, :requires]}, [do: [{:->, [line: 148], [[{:when, [line: 148], [{:x, [counter: -576460752303417885, line: 148], Kernel}, {{:., [line: 148], [:erlang, :or]}, [line: 148], [{{:., [line: 148], [:erlang, :"=:="]}, [line: 148], [{:x, [counter: -576460752303417885, line: 148], Kernel}, nil]}, {{:., [line: 148], [:erlang, :"=:="]}, [line: 148], [{:x, [counter: -576460752303417885, line: 148], Kernel}, false]}]}]}], []]}, {:->, [line: 148], [[{:x, [counter: -576460752303417885, line: 148], Kernel}], {:x, [counter: -576460752303417885, line: 148], Kernel}]}]]]}, verbose: false, version: false}
    (stdlib) :maps.update(:strict, {:case, [line: 151], [{{:., [line: 151], [Access, :get]}, [line: 151], [{:data, [line: 151], nil}, :strict]}, [do: [{:->, [line: 151], [[{:when, [line: 151], [{:x, [counter: -576460752303414180, line: 151], Kernel}, {{:., [line: 151], [:erlang, :or]}, [line: 151], [{{:., [line: 151], [:erlang, :"=:="]}, [line: 151], [{:x, [counter: -576460752303414180, line: 151], Kernel}, nil]}, {{:., [line: 151], [:erlang, :"=:="]}, [line: 151], [{:x, [counter: -576460752303414180, line: 151], Kernel}, false]}]}]}], false]}, {:->, [line: 151], [[{:x, [counter: -576460752303414180, line: 151], Kernel}], {:x, [counter: -576460752303414180, line: 151], Kernel}]}]]]}, %Credo.Config{all: false, check_for_updates: {:case, [line: 147], [{{:., [line: 147], [Access, :get]}, [line: 147], [{:data, [line: 147], nil}, :check_for_updates]}, [do: [{:->, [line: 147], [[{:when, [line: 147], [{:x, [counter: -576460752303414196, line: 147], Kernel}, {{:., [line: 147], [:erlang, :or]}, [line: 147], [{{:., [line: 147], [:erlang, :"=:="]}, [line: 147], [{:x, [counter: -576460752303414196, line: 147], Kernel}, nil]}, {{:., [line: 147], [:erlang, :"=:="]}, [line: 147], [{:x, [counter: -576460752303414196, line: 147], Kernel}, false]}]}]}], false]}, {:->, [line: 147], [[{:x, [counter: -576460752303414196, line: 147], Kernel}], {:x, [counter: -576460752303414196, line: 147], Kernel}]}]]]}, checks: {:checks_from_data, [line: 150], [{:data, [line: 150], nil}]}, crash_on_error: true, files: {:files_from_data, [line: 149], [{:data, [line: 149], nil}, {:dir, [line: 149], nil}]}, format: nil, help: false, ignore_checks: nil, lint_attribute_map: %{}, match_checks: nil, min_priority: 0, read_from_stdin: false, requires: {:case, [line: 148], [{{:., [line: 148], [Access, :get]}, [line: 148], [{:data, [line: 148], nil}, :requires]}, [do: [{:->, [line: 148], [[{:when, [line: 148], [{:x, [counter: -576460752303417885, line: 148], Kernel}, {{:., [line: 148], [:erlang, :or]}, [line: 148], [{{:., [line: 148], [:erlang, :"=:="]}, [line: 148], [{:x, [counter: -576460752303417885, line: 148], Kernel}, nil]}, {{:., [line: 148], [:erlang, :"=:="]}, [line: 148], [{:x, [counter: -576460752303417885, line: 148], Kernel}, false]}]}]}], []]}, {:->, [line: 148], [[{:x, [counter: -576460752303417885, line: 148], Kernel}], {:x, [counter: -576460752303417885, line: 148], Kernel}]}]]]}, verbose: false, version: false})
    lib/credo/config.ex:7: anonymous fn/2 in Credo.Config.__struct__/1
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding struct: Credo.Config.__struct__/1
    lib/credo/config.ex:146: Credo.Config.from_data/3
```

**Comment by rrrene** [comment]
Do you have an earlier version installed as an archive? You can check via `mix archive`!

**Comment by rrrene** [comment]
I will close this issue assuming you found a solution to this problem. (As I hinted at last year, it seems like you had another version of Credo installed as an archive).

Please re-open if this is still a problem!

**Comment by Dangeranger** [comment]
@rrrene Thank you. Sorry that I never closed this.
You were correct. I was the error.
