### ISSUE TITLE
Bug: Credo crashes checking an unquote(something)

### ISSUE THREAD

**Issue by ConnorRigby** [rrrene/credo#275]
### Environment

* Credo version (`mix credo -v`): 0.5.2

* Erlang/Elixir version (`elixir -v`): 1.3.3
* Operating system: Linux

### What were you trying to do?
This module is unable to be linted for some reason
``` elixir
defmodule Farmbot.StateTracker do
  @moduledoc """
    Common functionality for modules that need to track
    simple states that can be easily represented as a struct with key value
    pairs.
  """
  @callback load(any) :: {:ok, map}
  defmacro __using__(name: name, model: model) do
    quote do
      alias Farmbot.ConfigStorage, as: FBConfigStorage

      defmodule State, do: defstruct unquote(model)

      defp get_config(:all) do
        GenServer.call(FBConfigStorage, {:get, unquote(name), :all})
      end

      defp get_config(key) do
        GenServer.call(FBConfigStorage, {:get, unquote(name), key})
      end

      defp put_config(key, value) do
        GenServer.cast(FBConfigStorage, {:put, unquote(name), {key, value}})
      end

      @doc """
        Starts a #{unquote(name)} state tracker.
      """
      def start_link(), do: start_link([])
      def start_link(args),
        do: GenServer.start_link(unquote(name), args, name: unquote(name))

      def init(args) do
        n = Module.split(unquote(name)) |> List.last
        Logger.debug ">> is starting #{n}."
        case load(args) do
          {:ok, %State{} = state} ->
            {:ok, broadcast(state)}
          {:error, reason} ->
            Logger.error ">> encountered an error starting #{n}" <>
              "#{inspect reason}"
            Farmbot.factory_reset
          err ->
            Logger.error ">> encountered an unknown error in #{n}"
            <> ": #{inspect err}"
            Farmbot.factory_reset
        end
      end

      # this should be overriden.
      def load(_args), do: {:ok, %unquote(name).State{}}

      defp dispatch(reply, %unquote(name).State{} = state) do # THIS IS THE LINE IT ERRORS ON
        broadcast(state)
        {:reply, reply, state}
      end

      # If something bad happens in this module it's usually non recoverable.
      defp dispatch(_, {:error, reason}), do: dispatch({:error, reason})
      defp dispatch(%unquote(name).State{} = state) do
        broadcast(state)
        {:noreply, state}
      end

      defp dispatch({:error, reason}) do
        Logger.error ">> encountered a fatal error in #{unquote(name)}."
      end

      defp broadcast(%unquote(name).State{} = state) do
        GenServer.cast(Farmbot.BotState.Monitor, state)
        state
      end

      defp broadcast(_), do: dispatch {:error, :bad_dispatch}

      defoverridable [load: 1]
    end
  end
end

```

### Expected outcome
Expected to be checked (using the `--strict` option)

### Actual outcome
I get an error looking like this: 
```
** (FunctionClauseError) no function clause matching in Credo.Code.Name.full/1
    lib/credo/code/name.ex:29: Credo.Code.Name.full({:unquote, [line: 62], [{:name, [line: 62], nil}]})
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    lib/credo/code/name.ex:34: Credo.Code.Name.full/1
    lib/credo/code/module.ex:168: Credo.Code.Module.find_dependent_modules/2
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:262: Macro.do_traverse/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:262: Macro.do_traverse/4
```
I believe it starts from: 
``` elixir
defp dispatch(reply, %unquote(name).State{} = state)
```

**Comment by rrrene** [comment]
Thx for reporting! This will be released as part of `v0.6.0` which will be released this week! :+1:
