### ISSUE TITLE
`MultiAliasImportRequireUse` says it can be disabled, but can not be disabled

### ISSUE THREAD

**Issue by jclem** [rrrene/credo#306]
### Environment

* Credo version (`mix credo -v`): 0.6.0-rc1
* Erlang/Elixir version (`elixir -v`): 19.2/1.4.0
* Operating system: macOS 10.12.2

### What were you trying to do?

Run `mix credo --strict` with:

```
checks: [
  {Credo.Consistency.MultiAliasImportRequireUse, false}
]
```

in my .credo.exs

### Expected outcome

The `MultiAliasImportRequireUse` check would be skipped.

### Actual outcome

Running `mix credo --strict` exits with an error:

```
** (FunctionClauseError) no function clause matching in Access.fetch/2
    (elixir) lib/access.ex:239: Access.fetch(false, :priority)
    (elixir) lib/access.ex:269: Access.get/3
    lib/credo/check/runner.ex:70: anonymous fn/2 in Credo.Check.Runner.exclude_low_priority_checks/2
    (elixir) lib/enum.ex:1833: anonymous fn/3 in Enum.reject/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1833: Enum.reject/2
    lib/credo/check/runner.ex:67: Credo.Check.Runner.exclude_low_priority_checks/2
    lib/credo/check/runner.ex:40: Credo.Check.Runner.prepare_config/2
```

**Comment by jclem** [comment]
Ah, this appears to be fixed by RC2. Sorry!
