### ISSUE TITLE
Elixir.Credo.Check.Readability.Specs crash on unquote of def name

### ISSUE THREAD

**Issue by KronicDeth** [rrrene/credo#311]
### Environment

* Credo version (`mix credo -v`): `0.6.0`
* Erlang/Elixir version (`elixir -v`):  `19.2` / `1.4.0`
* Operating system: OSX

### What were you trying to do?

`mix credo --strict` on https://github.com/C-S-D/calcinator/tree/fe1459c836be649d5e27816d5957315dcd1a5683 after updating `credo` to `0.6.0`

#### Git Patch
```
diff --git a/mix.exs b/mix.exs
index 8a4e168..f40c42d 100644
--- a/mix.exs
+++ b/mix.exs
@@ -43,7 +43,7 @@ defmodule Calcinator.Mixfile do
       # JSONAPI document coding
       {:alembic, ">= 3.1.1 and < 3.2.0"},
       # Static Analysis
-      {:credo, "0.5.3", only: [:test]},
+      {:credo, "0.6.0", only: [:test]},
       # Type checking
       {:dialyze, "~> 0.2.1", only: :test},
       {:ex_doc, "~> 0.14.0", only: [:dev, :test]},
diff --git a/mix.lock b/mix.lock
index c9b25a8..6f523c4 100644
--- a/mix.lock
+++ b/mix.lock
@@ -1,6 +1,6 @@
 %{"alembic": {:hex, :alembic, "3.1.1", "5d06c655b238369c8e0ee9206fdde1bdb8a45dbc5129b9091a0fe0883403c0c8", [:mix], [{:ecto, "~> 2.0", [hex: :ecto, optional: false]}, {:poison, "~> 1.5 or ~> 2.0", [hex: :poison, optional: false]}]},
-  "bunt": {:hex, :bunt, "0.1.6", "5d95a6882f73f3b9969fdfd1953798046664e6f77ec4e486e6fafc7caad97c6f", [:mix], []},
-  "credo": {:hex, :credo, "0.5.3", "0c405b36e7651245a8ed63c09e2d52c2e2b89b6d02b1570c4d611e0fcbecf4a2", [:mix], [{:bunt, "~> 0.1.6", [hex: :bunt, optional: false]}]},
+  "bunt": {:hex, :bunt, "0.2.0", "951c6e801e8b1d2cbe58ebbd3e616a869061ddadcc4863d0a2182541acae9a38", [:mix], []},
+  "credo": {:hex, :credo, "0.6.0", "44a82f82b94eeb4ba6092c89b8a6730ca1a3291c7940739d5acc8806d25ac991", [:mix], [{:bunt, "~> 0.2.0", [hex: :bunt, optional: false]}]},
   "decimal": {:hex, :decimal, "1.3.1", "157b3cedb2bfcb5359372a7766dd7a41091ad34578296e951f58a946fcab49c6", [:mix], []},
   "dialyze": {:hex, :dialyze, "0.2.1", "9fb71767f96649020d769db7cbd7290059daff23707d6e851e206b1fdfa92f9d", [:mix], []},
   "earmark": {:hex, :earmark, "1.0.3", "89bdbaf2aca8bbb5c97d8b3b55c5dd0cff517ecc78d417e87f1d0982e514557b", [:mix], []},
```

### Expected outcome

No crash

### Actual outcome

```
Checking 27 source files ...
Error while running Elixir.Credo.Check.Readability.Specs on lib/calcinator/controller.ex
** (EXIT from #PID<0.70.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 385], [{:quoted_name, [line: 385], nil}]}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
        lib/credo/source_file.ex:54: Credo.SourceFile.column/3
        lib/credo/check.ex:149: Credo.Check.add_custom_column/5
        lib/credo/check.ex:133: Credo.Check.format_issue/5
        lib/credo/check/readability/specs.ex:49: Credo.Check.Readability.Specs.traverse/4
        (elixir) lib/macro.ex:276: Macro.do_traverse/4
        (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

[Line 385 of `lib/calcinator/controller.ex`](https://github.com/C-S-D/calcinator/blob/fe1459c836be649d5e27816d5957315dcd1a5683/lib/calcinator/controller.ex#L385): ` def unquote(quoted_name)(conn, params) do` in

```
  defp quoted_action(quoted_name, quoted_configuration) do
      quote do
        def unquote(quoted_name)(conn, params) do
          Calcinator.Controller.unquote(quoted_name)(conn, params, unquote(quoted_configuration))
        end
      end
    end
```

**Comment by joshuawscott** [comment]
I'm getting the same thing, with the following macro:
```
  defmacro defconfig(mod_key, keys) do
    [keys] |> List.flatten |> Enum.map(fn(key) ->
      quote do
        def unquote(key)() do
          Application.get_env(unquote(mod_key), unquote(key))
        end
      end
    end)
  end
```

**Comment by rrrene** [comment]
@KronicDeth @joshuawscott `v0.6.1` contains a fix.

If it still breaks, please swear at me in this issue :wink:
