### ISSUE TITLE
Credo fails on :unquote

### ISSUE THREAD

**Issue by walkr** [rrrene/credo#329]
I'm working on a Phoenix app, which has as dependencies other custom apps.
It looks like every time I have this pattern (generating functions) in my libraries, credo fails to run:

Complaint is on line 36.

```elixir
  # Example

  for level <- [:debug, :info, :warn, :error] do
    def unquote(level)(message, details \\ []) do  #line 36
      report(unquote(level), message, details)
    end
  end
```

### Environment

* Credo version (`mix credo -v`): 0.6.1
* Erlang/Elixir version (`elixir -v`): 1.4.1
* Operating system: MacOS

### What were you trying to do?

Run credo normally

### Expected outcome

It should not fail

### Actual outcome

```shell
Error while running Elixir.Credo.Check.Readability.Specs on apps/reporter/lib/reporter.ex
** (EXIT from #PID<0.70.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 36], [{:level, [line: 36], nil}]}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
        lib/credo/source_file.ex:54: Credo.SourceFile.column/3
        lib/credo/check.ex:149: Credo.Check.add_custom_column/5
        lib/credo/check.ex:133: Credo.Check.format_issue/5
        lib/credo/check/readability/specs.ex:49: Credo.Check.Readability.Specs.traverse/4
        (elixir) lib/macro.ex:276: Macro.do_traverse/4
        (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

Any thoughts?

Thank you!

**Comment by walkr** [comment]
My apologies. I was running credo 0.6.0 in my main app.
Issue does not exist in 0.6.1
