### ISSUE TITLE
Explain for Credo.Check.Refactor.VariableRebinding raises protocol Enumerable not implemented for nil

### ISSUE THREAD

**Issue by fertapric** [rrrene/credo#411]
### Environment

* Credo version (`mix credo -v`): 0.8.3
* Erlang/Elixir version (`elixir -v`): 1.4.4
* Operating system: Darwin 16.6.0 x86_64

### What were you trying to do?

Use credo's explain.

### Expected outcome

Explanation

### Actual outcome

```
┃
┃   [F] Category: refactor
┃    →  Priority: normal
┃
┃       Variable "conn" was declared more than once.
┃       test/web/controllers/users_controller_test.exs:31:5
┃
┃    __ CODE IN QUESTION
┃
┃    29     assert redirected_to(conn) == invoice_path(conn, :show, id)
┃    30
┃    31     conn = get conn, invoice_path(conn, :show, id)
┃           ^^^^
┃    32     assert html_response(conn, 200) =~ "Show Invoice"
┃    33   end
┃
┃    __ WHY IT MATTERS
┃
┃       You might want to refrain from rebinding variables.
┃
┃       Although technically fine, rebinding to the same name can lead to less
┃       precise naming.
┃
┃       Consider this example:
┃
┃           def find_a_good_time do
┃             time = MyApp.DateTime.now
┃             time = MyApp.DateTime.later(time, 5, :days)
┃             {:ok, time} = verify_available_time(time)
┃
┃             time
┃           end
┃
┃       While there is nothing wrong with this, many would consider the following
┃       implementation to be easier to comprehend:
┃
┃           def find_a_good_time do
┃             today = DateTime.now
┃             proposed_time = DateTime.later(today, 5, :days)
┃             {:ok, verified_time} = verify_available_time(proposed_time)
┃
┃             verified_time
┃           end
┃
┃    __ CONFIGURATION OPTIONS
┃
┃       To configure this check, use this tuple
┃
┃         {Credo.Check.Refactor.VariableRebinding, <params>}
┃
┃       with <params> being false or any combination of these keywords:
┃
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1776: Enum.reduce/3
    lib/credo/cli/output/explain.ex:335: Credo.CLI.Output.Explain.get_params_indent/2
    lib/credo/cli/output/explain.ex:306: Credo.CLI.Output.Explain.print_params_explanation/4
    lib/credo/cli/output/explain.ex:195: Credo.CLI.Output.Explain.print_issue/3
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
```

**Comment by rrrene** [comment]
Ouch! Thx for reporting this! :+1:
