### ISSUE TITLE
Error: Credo.Check.Consistency.ParameterPatternMatching.elixir_version/0 is undefined or private

### ISSUE THREAD

**Issue by bangn** [rrrene/credo#415]
### Environment

* Credo version (`mix credo -v`): 0.8.4
* Erlang/Elixir version (`elixir -v`): 1.4.5
* Operating system: OSX Sierra

### What were you trying to do?

I tried to run `mix credo` in `credo` repo itself.

### Expected outcome

It should run.

### Actual outcome
Got below exception.

```
~/dev/projects/elixir/credo$ mix credo
** (UndefinedFunctionError) function Credo.Check.Consistency.ParameterPatternMatching.elixir_version/0 is undefined or private
    Credo.Check.Consistency.ParameterPatternMatching.elixir_version()
    lib/credo/check/runner.ex:114: Credo.Check.Runner.matches_requirement?/2
    (elixir) lib/enum.ex:1833: anonymous fn/3 in Enum.reject/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1833: Enum.reject/2
    lib/credo/check/runner.ex:104: Credo.Check.Runner.exclude_checks_based_on_elixir_version/1
    lib/credo/cli/command/suggest.ex:19: Credo.CLI.Command.Suggest.run/1
    lib/credo/execution/task.ex:36: Credo.Execution.Task.run/3
```

**Comment by bangn** [comment]
Looks like reinstall erlang and credo helps.
