### ISSUE TITLE
Crash when using --strict

### ISSUE THREAD

**Issue by lukaszsamson** [rrrene/credo#455]
### Environment

* Credo version (`mix credo -v`): 0.8.7
* Erlang/Elixir version (`elixir -v`): 1.5.2, 20.1
* Operating system: macOS 10.13

### What were you trying to do?
`mix credo --strict` in umbrella phoenix app

### Expected outcome
no crash

### Actual outcome
```
$ mix credo --strict
info: Some source files could not be parsed correctly and are excluded:

   1) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.embedded/embedded_schema.ex
   2) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.json/changeset_view.ex
   3) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.json/changeset_view.ex
   4) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.html/view.ex
   5) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.json/controller_test.exs
   6) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.json/view.ex
   7) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.channel/channel.ex
   8) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.html/controller_test.exs
   9) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.model/migration.exs
  10) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.html/controller.ex
  11) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.schema/migration.exs
  12) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.channel/channel.ex
  13) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.json/controller.ex
  14) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.json/view.ex
  15) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.json/controller_test.exs
  16) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.context/schema_access.ex
  17) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.context/context.ex
  18) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.context/test_cases.exs
  19) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.model/model_test.exs
  20) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.model/model.ex
  21) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.html/controller.ex
  22) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.context/context_test.exs
  23) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.json/controller.ex
  24) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.channel/channel_test.exs
  25) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.html/controller_test.exs
  26) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.channel/channel_test.exs
  27) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.json/fallback_controller.ex
  28) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.presence/presence.ex
  29) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.schema/schema.ex
  30) apps/backoffice/node_modules/phoenix/priv/templates/phoenix.gen.html/view.ex
  31) apps/backoffice/node_modules/phoenix/priv/templates/phx.gen.context/access_no_schema.ex

Checking 368 source files (this might take a while) ...
Error while running Elixir.Credo.Check.Readability.ParenthesesOnZeroArityDefs on apps/backoffice/node_modules/phoenix/lib/phoenix/template.ex
** (EXIT from #PID<0.73.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:776: Enum.fetch/2
        (elixir) lib/enum.ex:311: Enum.at/3
        lib/credo/check/readability/parentheses_on_zero_arity_defs.ex:37: Credo.Check.Readability.ParenthesesOnZeroArityDefs.traverse/3
        (elixir) lib/macro.ex:379: anonymous fn/4 in Macro.do_traverse_args/4
        (elixir) lib/enum.ex:1372: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:345: Macro.do_traverse/4
        (elixir) lib/enum.ex:1372: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3


13:53:08.539 [error] Task #PID<0.772.0> started from #PID<0.73.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:776: Enum.fetch/2
    (elixir) lib/enum.ex:311: Enum.at/3
    lib/credo/check/readability/parentheses_on_zero_arity_defs.ex:37: Credo.Check.Readability.ParenthesesOnZeroArityDefs.traverse/3
    (elixir) lib/macro.ex:379: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1372: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:345: Macro.do_traverse/4
    (elixir) lib/enum.ex:1372: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
Function: #Function<14.20071509/0 in Credo.Check.Runner.run/2>
    Args: []

13:53:08.549 [error] GenServer Credo.Supervisor terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:776: Enum.fetch/2
    (elixir) lib/enum.ex:311: Enum.at/3
    lib/credo/check/readability/parentheses_on_zero_arity_defs.ex:37: Credo.Check.Readability.ParenthesesOnZeroArityDefs.traverse/3
    (elixir) lib/macro.ex:379: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1372: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:345: Macro.do_traverse/4
    (elixir) lib/enum.ex:1372: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
Last message: {:EXIT, #PID<0.73.0>, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: nil}, [{Enumerable, :impl_for!, 1, [file: 'lib/enum.ex', line: 1]}, {Enum, :fetch, 2, [file: 'lib/enum.ex', line: 776]}, {Enum, :at, 3, [file: 'lib/enum.ex', line: 311]}, {Credo.Check.Readability.ParenthesesOnZeroArityDefs, :traverse, 3, [file: 'lib/credo/check/readability/parentheses_on_zero_arity_defs.ex', line: 37]}, {Macro, :"-do_traverse_args/4-fun-0-", 4, [file: 'lib/macro.ex', line: 379]}, {Enum, :"-map_reduce/3-lists^mapfoldl/2-0-", 3, [file: 'lib/enum.ex', line: 1372]}, {Macro, :do_traverse, 4, [file: 'lib/macro.ex', line: 345]}, {Enum, :"-map_reduce/3-lists^mapfoldl/2-0-", 3, [file: 'lib/enum.ex', line: 1372]}]}}
State: {:state, {:local, Credo.Supervisor}, :one_for_one, [{:child, #PID<0.220.0>, Credo.Service.SourceFileSource, {Credo.Service.SourceFileSource, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileSource]}, {:child, #PID<0.219.0>, Credo.Service.SourceFileLines, {Credo.Service.SourceFileLines, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileLines]}, {:child, #PID<0.218.0>, Credo.Service.SourceFileAST, {Credo.Service.SourceFileAST, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileAST]}, {:child, #PID<0.217.0>, Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {:child, #PID<0.216.0>, Credo.Service.Commands, {Credo.Service.Commands, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.Commands]}, {:child, #PID<0.215.0>, Credo.CLI.Output.Shell, {Credo.CLI.Output.Shell, :start_link, []}, :permanent, 5000, :worker, [Credo.CLI.Output.Shell]}], :undefined, 3, 5, [], 0, Supervisor.Default, {[{Credo.CLI.Output.Shell, {Credo.CLI.Output.Shell, :start_link, []}, :permanent, 5000, :worker, [Credo.CLI.Output.Shell]}, {Credo.Service.Commands, {Credo.Service.Commands, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.Commands]}, {Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {Credo.Service.SourceFileAST, {Credo.Service.SourceFileAST, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileAST]}, {Credo.Service.SourceFileLines, {Credo.Service.SourceFileLines, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileLines]}, {Credo.Service.SourceFileSource, {Credo.Service.SourceFileSource, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileSource]}], [strategy: :one_for_one]}}
```

**Comment by rrrene** [comment]
Thanks for reporting this 😀  This problem does not seem to originate from Credo being run in an umbrella app.

It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**On a side note**: Why are there Elixir files in your `node_modules` folder?
