### ISSUE TITLE
MatchInCondition fails for Ecto query

### ISSUE THREAD

**Issue by h4cc** [rrrene/credo#535]
### Environment

* Credo version (`mix credo -v`): 0.9.2
* Erlang/Elixir version (`elixir -v`): Elixir 1.6.1 (compiled with OTP 19)
* Operating system: Ubuntu 16.04

### What were you trying to do?

Check a file

> mix credo foo.ex

Content:

```
defmodule Foo do

  def fetch_foos_by_id(gateway_id) do
    query = from if in FooInterface,
             join: is in assoc(if, :instance),
             join: d in assoc(if, :device),
             where: fragment("upper(?->>'foo_id') = ?", if.opts, ^gateway_id) and is.driver == ^"FooBar",
             preload: [device: d, instance: is]

    Repo.all(query)
  end

end
```

### Expected outcome

No crash

### Actual outcome

Crash like this:

```
Error while running Elixir.Credo.Check.Refactor.MatchInCondition on foo.ex
** (EXIT from #PID<0.74.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:141: Enumerable.reduce/3
        (elixir) lib/enum.ex:1919: Enum.reject/2
        lib/credo/check/refactor/match_in_condition.ex:57: Credo.Check.Refactor.MatchInCondition.traverse/3
        (elixir) lib/macro.ex:277: anonymous fn/4 in Macro.do_traverse_args/4
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:243: Macro.do_traverse/4
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

**Comment by h4cc** [comment]
Too bad none of the `# credo:disable-...` commends helps in this case :(
