### ISSUE TITLE
Elixir.Credo.Check.Design.AliasUsage throw exception

### ISSUE THREAD

**Issue by tim2CF** [rrrene/credo#537]
### Environment

* Credo version (`mix credo -v`): "0.9.2"
* Erlang/Elixir version (`elixir -v`): "1.6.4"
* Operating system: mac

### What were you trying to do?

`mix credo`

### Actual outcome

```
Iljas-iMac:lab_flask timcf$ mix credo
Ignoring an undefined check: Credo.Check.Warning.NameRedeclarationByAssignment
Ignoring an undefined check: Credo.Check.Warning.NameRedeclarationByCase
Ignoring an undefined check: Credo.Check.Warning.NameRedeclarationByDef
Ignoring an undefined check: Credo.Check.Warning.NameRedeclarationByFn
Checking 20 source files ...
Error while running Elixir.Credo.Check.Design.AliasUsage on lib/helpers/macro.ex
** (EXIT from #PID<0.73.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 184, column: 17], [{:module, [line: 184, column: 25], nil}]}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
        (elixir) lib/enum.ex:2751: anonymous fn/3 in Enum.join/2
        (elixir) lib/enum.ex:1899: Enum."-join/2-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1899: Enum.join/2
        lib/credo/code/scope.ex:43: Credo.Code.Scope.name/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2


16:53:10.264 [error] Task #PID<0.256.0> started from #PID<0.73.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 184, column: 17], [{:module, [line: 184, column: 25], nil}]}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
    (elixir) lib/enum.ex:2751: anonymous fn/3 in Enum.join/2
    (elixir) lib/enum.ex:1899: Enum."-join/2-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1899: Enum.join/2
    lib/credo/code/scope.ex:43: Credo.Code.Scope.name/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
Function: #Function<10.89534668/0 in Credo.Check.Runner.run/2>
    Args: []

16:53:10.272 [error] GenServer Credo.Supervisor terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 184, column: 17], [{:module, [line: 184, column: 25], nil}]}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
    (elixir) lib/enum.ex:2751: anonymous fn/3 in Enum.join/2
    (elixir) lib/enum.ex:1899: Enum."-join/2-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1899: Enum.join/2
    lib/credo/code/scope.ex:43: Credo.Code.Scope.name/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
Last message: {:EXIT, #PID<0.73.0>, {%Protocol.UndefinedError{description: "", protocol: String.Chars, value: {:unquote, [line: 184, column: 17], [{:module, [line: 184, column: 25], nil}]}}, [{String.Chars, :impl_for!, 1, [file: 'lib/string/chars.ex', line: 3]}, {String.Chars, :to_string, 1, [file: 'lib/string/chars.ex', line: 22]}, {Enum, :"-join/2-fun-0-", 3, [file: 'lib/enum.ex', line: 2751]}, {Enum, :"-join/2-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1899]}, {Enum, :join, 2, [file: 'lib/enum.ex', line: 1899]}, {Credo.Code.Scope, :name, 2, [file: 'lib/credo/code/scope.ex', line: 43]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1294]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1294]}]}}
State: {:state, {:local, Credo.Supervisor}, :one_for_one, [{:child, #PID<0.223.0>, Credo.Service.SourceFileSource, {Credo.Service.SourceFileSource, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileSource]}, {:child, #PID<0.222.0>, Credo.Service.SourceFileLines, {Credo.Service.SourceFileLines, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileLines]}, {:child, #PID<0.221.0>, Credo.Service.SourceFileAST, {Credo.Service.SourceFileAST, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileAST]}, {:child, #PID<0.220.0>, Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {:child, #PID<0.219.0>, Credo.Service.Commands, {Credo.Service.Commands, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.Commands]}, {:child, #PID<0.218.0>, Credo.CLI.Output.Shell, {Credo.CLI.Output.Shell, :start_link, []}, :permanent, 5000, :worker, [Credo.CLI.Output.Shell]}], :undefined, 3, 5, [], 0, Supervisor.Default, {:ok, {%{intensity: 3, period: 5, strategy: :one_for_one}, [{Credo.CLI.Output.Shell, {Credo.CLI.Output.Shell, :start_link, []}, :permanent, 5000, :worker, [Credo.CLI.Output.Shell]}, {Credo.Service.Commands, {Credo.Service.Commands, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.Commands]}, {Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {Credo.Service.SourceFileAST, {Credo.Service.SourceFileAST, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileAST]}, {Credo.Service.SourceFileLines, {Credo.Service.SourceFileLines, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileLines]}, {Credo.Service.SourceFileSource, {Credo.Service.SourceFileSource, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileSource]}]}}}
```

I also tried to comment out `AliasUsage` line from `.credo.exs` - it not helped

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by tim2CF** [comment]
thanks, solved!

**Comment by tim2CF** [comment]
the same issue for other check

```
Error while running Elixir.Credo.Check.Design.TagTODO on lib/helpers/macro.ex
** (EXIT from #PID<0.74.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 194, column: 17], [{:module, [line: 194, column: 25], nil}]}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
        (elixir) lib/enum.ex:2751: anonymous fn/3 in Enum.join/2
        (elixir) lib/enum.ex:1899: Enum."-join/2-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1899: Enum.join/2
        lib/credo/code/scope.ex:43: Credo.Code.Scope.name/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
```
