### ISSUE TITLE
Unexpected exception in Credo.Check.Consistency.SpaceInParentheses

### ISSUE THREAD

**Issue by ntalfer** [rrrene/credo#556]
### Environment

* Credo version (`mix credo -v`): 0.9.3
* Erlang/Elixir version (`elixir -v`): Erlang/OTP 18 + Elixir 1.4.2
* Operating system: Ubuntu 14.04

### What were you trying to do?

mix credo foo.ex where foo.ex has the following content:

````
defmodule Foo do
  def bar(items) do
    """
    #{for {item, i} <- Enum.with_index(items) do
    "item #{i + 1}:" <> item <> "\n"
    end
    }
    """
  end
end
````

There is no compilation problem with this module and works like a charm:

````
Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Foo.bar(["a", "b"])
"item 1:a\nitem 2:b\n\n"
````

### Expected outcome

get credo report

### Actual outcome

````
Checking 1 source file ...
Error while running Elixir.Credo.Check.Consistency.SpaceInParentheses
** (EXIT from #PID<0.46.0>) an exception was raised:
    ** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must contain only:

  * strings
  * integers representing Unicode codepoints
  * or a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

["item ", {{6, 7, 15}, [{:identifier, {6, 9, 10}, :i}, {:dual_op, {6, 11, 12}, :+}, {:number, {6, 13, 14}, 1}]}, ":"]

        (elixir) lib/list.ex:709: List.to_string/1
        lib/credo/code/token.ex:227: Credo.Code.Token.PositionHelper.to_col_end/3
        lib/credo/code/token.ex:207: Credo.Code.Token.PositionHelper.convert_to_col_end/3
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/credo/code/token.ex:132: Credo.Code.Token.PositionHelper.position_tuple_for_quoted_string/3
        lib/credo/code/token.ex:88: Credo.Code.Token.PositionHelper.position/1
        lib/credo/code/token.ex:245: Credo.Code.Token.ElixirPre1_6_0.position/2
        lib/credo/code/interpolation_helper.ex:157: Credo.Code.InterpolationHelper.find_interpolations/2

09:24:25.432 [error] Task #PID<0.266.0> started from #PID<0.46.0> terminating
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must contain only:

  * strings
  * integers representing Unicode codepoints
  * or a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

["item ", {{6, 7, 15}, [{:identifier, {6, 9, 10}, :i}, {:dual_op, {6, 11, 12}, :+}, {:number, {6, 13, 14}, 1}]}, ":"]

    (elixir) lib/list.ex:709: List.to_string/1
    lib/credo/code/token.ex:227: Credo.Code.Token.PositionHelper.to_col_end/3
    lib/credo/code/token.ex:207: Credo.Code.Token.PositionHelper.convert_to_col_end/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/credo/code/token.ex:132: Credo.Code.Token.PositionHelper.position_tuple_for_quoted_string/3
    lib/credo/code/token.ex:88: Credo.Code.Token.PositionHelper.position/1
    lib/credo/code/token.ex:245: Credo.Code.Token.ElixirPre1_6_0.position/2
    lib/credo/code/interpolation_helper.ex:157: Credo.Code.InterpolationHelper.find_interpolations/2
Function: #Function<7.64089555/0 in Credo.Check.Runner.run_checks_that_run_on_all/2>
    Args: []

09:24:25.441 [error] GenServer Credo.Supervisor terminating
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must contain only:

  * strings
  * integers representing Unicode codepoints
  * or a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

["item ", {{6, 7, 15}, [{:identifier, {6, 9, 10}, :i}, {:dual_op, {6, 11, 12}, :+}, {:number, {6, 13, 14}, 1}]}, ":"]

    (elixir) lib/list.ex:709: List.to_string/1
    lib/credo/code/token.ex:227: Credo.Code.Token.PositionHelper.to_col_end/3
    lib/credo/code/token.ex:207: Credo.Code.Token.PositionHelper.convert_to_col_end/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/credo/code/token.ex:132: Credo.Code.Token.PositionHelper.position_tuple_for_quoted_string/3
    lib/credo/code/token.ex:88: Credo.Code.Token.PositionHelper.position/1
    lib/credo/code/token.ex:245: Credo.Code.Token.ElixirPre1_6_0.position/2
    lib/credo/code/interpolation_helper.ex:157: Credo.Code.InterpolationHelper.find_interpolations/2
Last message: {:EXIT, #PID<0.46.0>, {%ArgumentError{message: "cannot convert the given list to a string.\n\nTo be converted to a string, a list must contain only:\n\n  * strings\n  * integers representing Unicode codepoints\n  * or a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[\"item \", {{6, 7, 15}, [{:identifier, {6, 9, 10}, :i}, {:dual_op, {6, 11, 12}, :+}, {:number, {6, 13, 14}, 1}]}, \":\"]\n"}, [{List, :to_string, 1, [file: 'lib/list.ex', line: 709]}, {Credo.Code.Token.PositionHelper, :to_col_end, 3, [file: 'lib/credo/code/token.ex', line: 227]}, {Credo.Code.Token.PositionHelper, :convert_to_col_end, 3, [file: 'lib/credo/code/token.ex', line: 207]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1755]}, {Credo.Code.Token.PositionHelper, :position_tuple_for_quoted_string, 3, [file: 'lib/credo/code/token.ex', line: 132]}, {Credo.Code.Token.PositionHelper, :position, 1, [file: 'lib/credo/code/token.ex', line: 88]}, {Credo.Code.Token.ElixirPre1_6_0, :position, 2, [file: 'lib/credo/code/token.ex', line: 245]}, {Credo.Code.InterpolationHelper, :find_interpolations, 2, [file: 'lib/credo/code/interpolation_helper.ex', line: 157]}]}}
State: {:state, {:local, Credo.Supervisor}, :one_for_one, [{:child, #PID<0.258.0>, Credo.Service.SourceFileSource, {Credo.Service.SourceFileSource, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileSource]}, {:child, #PID<0.257.0>, Credo.Service.SourceFileLines, {Credo.Service.SourceFileLines, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileLines]}, {:child, #PID<0.256.0>, Credo.Service.SourceFileAST, {Credo.Service.SourceFileAST, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileAST]}, {:child, #PID<0.255.0>, Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {:child, #PID<0.254.0>, Credo.Service.Commands, {Credo.Service.Commands, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.Commands]}, {:child, #PID<0.253.0>, Credo.CLI.Output.Shell, {Credo.CLI.Output.Shell, :start_link, []}, :permanent, 5000, :worker, [Credo.CLI.Output.Shell]}], :undefined, 3, 5, [], 0, Supervisor.Default, {:ok, {{:one_for_one, 3, 5}, [{Credo.CLI.Output.Shell, {Credo.CLI.Output.Shell, :start_link, []}, :permanent, 5000, :worker, [Credo.CLI.Output.Shell]}, {Credo.Service.Commands, {Credo.Service.Commands, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.Commands]}, {Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {Credo.Service.SourceFileAST, {Credo.Service.SourceFileAST, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileAST]}, {Credo.Service.SourceFileLines, {Credo.Service.SourceFileLines, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileLines]}, {Credo.Service.SourceFileSource, {Credo.Service.SourceFileSource, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileSource]}]}}}
````

**Comment by rrrene** [comment]
Thx for reporting! :+1:

**Comment by rrrene** [comment]
@ntalfer This is a problem in Elixir 1.4 and 1.5 - can you test this with Elixir 1.6 or 1.7?

**Comment by rrrene** [comment]
@ntalfer Any news on this one?

**Comment by rrrene** [comment]
@ntalfer :+1:
