### ISSUE TITLE
[noob elixir question] mix credo fails with "undefined function Bunt.puts"

### ISSUE THREAD

**Issue by jmgarnier** [rrrene/credo#58]
I am learning Elixir since a couple of days so I don't have much background to debug this. My goal was to use `credo` while I learn the language after I heard good feedback on it :wink: 

I have added `credo` to my `mix.exs` and then I ran the following commands: 

```
~/Code/elixir/hello_elixir  15:18:03
$ mix deps.get                                                                                                                                                          ruby-2.2.3
Running dependency resolution
All dependencies up to date

~/Code/elixir/hello_elixir  15:18:11
$ mix deps                                                                                                                                                              ruby-2.2.3
* bunt 0.1.5 (Hex package) (mix)
  locked at 0.1.5 (bunt)
  ok
* credo 0.3.10 (Hex package) (mix)
  locked at 0.3.10 (credo)
  ok

~/Code/elixir/hello_elixir  15:18:15
$ mix credo                                                                                                                                                             ruby-2.2.3
** (UndefinedFunctionError) undefined function Bunt.puts/1 (module Bunt is not available)
    Bunt.puts("Checking 1 source file ...")
    lib/credo/cli/command/suggest.ex:19: Credo.CLI.Command.Suggest.run/2
    lib/credo/cli.ex:53: Credo.CLI.main/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

**Comment by 21croissants** [comment]
Found the answer. This is because I was trying to setup [Credo for flycheck on spacemacs](https://github.com/smeevil/flycheck-elixir-credo) and I had installed the archive credo without blunt.

What I did to fix it:
```
$ git clone https://github.com/rrrene/bunt                                                                                                                               
Cloning into 'bunt'...
cd bunt
remote: Counting objects: 89, done.
remote: Total 89 (delta 0), reused 0 (delta 0), pack-reused 89
Unpacking objects: 100% (89/89), done.
Checking connectivity... done.

~/Code/elixir  15:25:30
$ cd bunt                                                                                                                                                              
~/Code/elixir/bunt on ⭠ master (40d18h46m) 15:25:30
$ mix archive.build                                                                                                                                                    
Generated archive "bunt-0.1.4.ez" with MIX_ENV=dev

~/Code/elixir/bunt on ⭠ master (40d18h46m) 15:25:38
$ mix archive.install                                                                                                                                                  
Are you sure you want to install archive "bunt-0.1.4.ez"? [Yn] Y
* creating /Users/jm/.mix/archives/bunt-0.1.4.ez

~/Code/elixir/bunt on ⭠ master (40d18h46m) 15:25:49
$ mix archive                                                                                                                                                          ruby-2.2.3
* bunt-0.1.4.ez
* credo-0.3.10.ez
* hex-0.11.3.ez
Archives installed at: /Users/jm/.mix/archives

~/Code/elixir/bunt on ⭠ master (40d18h46m) 15:25:55
$ cd ../hello_elixir                                                                                                                                                   

~/Code/elixir/hello_elixir  15:26:00
$ mix credo                                                                                                                                                            
Checking 1 source file ...

  Code Readability
┃
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/hello_elixir.ex:1:11 (HelloElixir)

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 0.2 seconds (0.00s to load, 0.2s running checks)
1 mods/funs, found 1 code readability issue.

Showing priority issues: ↑ ↗ →  (use `--strict` to show all issues, `--help` for options).
```

**Comment by rrrene** [comment]
This is very valuable input. Thank you for that!

I'm currently on a trip and can't do much, but I would like to keep this issue open so I see it when I come home!

Thx again for reporting! 👍🏻

**Comment by smeevil** [comment]
@21croissants I'll add it to the readme :) Did the flycheck work for you (sorry for hijacking the thread @rrrene ) if not , let me know in the repo and I'll see what i can do.

**Comment by sstern6** [comment]
@rrrene I believe we can close this because the readme has specific instructions of how to build and install bunt when cloning.

Thoughts

**Comment by rrrene** [comment]
@sstern6 You are right.
