### ISSUE TITLE
explain on file ending results in FunctionClauseError

### ISSUE THREAD

**Issue by eagle-te** [rrrene/credo#635]
### Precheck

* Did a quick search, but no similar issue was found
* So far this issue was reproducible with another file
* college can reproduce issue

### Environment

* Credo version: 1.0.2
* Erlang version: OTP 21 (21.2)
* Elixir version: 1.7.4 (in project with asdf), actual: 1.8.0
* Operating system: Linux, dist:Manjaro, kernel:4.20.7-1-MANJARO
* Operating system (college): Linux, dist:debian, kernel:4.19.0-2-amd64

### What were you trying to do?
Executing `mix credo --strict` on a specific readability issue regarding line ending.
While just executing `mix credo --strict` on the file alone runs fine:
```elixir
$ mix credo --strict test/support/helper.ex  
Checking 1 source file ...

  Code Readability                                                              
┃ 
┃ [R] ↘ There should be a final \n at the end of each file.
┃       test/support/helper.ex:9 #(Projectname.Helper.flash_messages_contain)

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 0.1 seconds (0.01s to load, 0.1s running checks)
2 mods/funs, found 1 code readability issue.
```

### Expected outcome
Correct displayed explanation of the issue.

### Actual outcome
```elixir
$ mix credo --strict test/support/helper.ex:9

Checking 1 source file ...

  Projectname.Helper                                                                    
┃ 
┃   [R] Category: readability 
┃    ↘  Priority: low 
┃ 
┃       There should be a final \n at the end of each file.
┃       test/support/helper.ex:9 (Projectname.Helper.flash_messages_contain)
┃ 
┃    __ CODE IN QUESTION
┃ 
┃     7     |> Enum.any?(fn (item) -> String.contains?(elem(item, 1), text) end)
┃     8   end
┃     9 end
** (FunctionClauseError) no function clause matching in String.Unicode.length/1    
    
    The following arguments were given to String.Unicode.length/1:
    
        # 1
        nil
    
    (elixir) lib/elixir/unicode/unicode.ex:255: String.Unicode.length/1
    lib/credo/cli/output/ui.ex:89: Credo.CLI.Output.UI.truncate/3
    lib/credo/cli/command/explain/output/default.ex:235: Credo.CLI.Command.Explain.Output.Default.print_source_line/5
    lib/credo/cli/command/explain/output/default.ex:496: Credo.CLI.Command.Explain.Output.Default.print_issue_line_no/5
    lib/credo/cli/command/explain/output/default.ex:186: Credo.CLI.Command.Explain.Output.Default.print_issue/3
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    lib/credo/cli/command/explain/explain_command.ex:38: Credo.CLI.Command.Explain.ExplainCommand.print_results_and_summary/1
```

**Comment by rrrene** [comment]
@eagle-te :+1:
