### ISSUE TITLE
credo@1.1.0 crashes, when sourcecode contain unicode heredoc

### ISSUE THREAD

**Issue by bencode** [rrrene/credo#665]
# Environment

* Credo version (`mix credo -v`):
1.1.0

* Erlang/Elixir version (`elixir -v`):

```
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.0 (compiled with Erlang/OTP 22)
```

* Operating system:

MacOS

### What were you trying to do?

```
mix credo
```

### Actual outcome
<img width="120" alt="Screenshot 2019-06-25 at 9 16 18 PM" src="https://user-images.githubusercontent.com/769981/60101599-9efc5d00-978e-11e9-92f1-cefb8bd4c908.png">

### may be reason

in function [pad_replaced_heredoc](https://github.com/rrrene/credo/blame/master/lib/credo/code/heredocs.ex#L249)  `length_after_byte_index` my be minus

**Comment by rrrene** [comment]
@bencode Thx for reporting! :+1:

Could you provide the heredoc that caused the crash or is the information sensitive? I tried to reproduce this in 2664240 to no avail.

**Comment by bencode** [comment]
@rrrene try this file 
https://gist.github.com/bencode/1c3d9f7af4c71d165ce2f5d84d030505#file-test-for-credo

**Comment by skovmand** [comment]
I have the same issue in two modules. It goes away when I remove all the `@doc` blocks from the modules or if I disable the `MaxLineLength` check. There is only text in the doc blocks. The stack traces (with removed code, it's a private project).

```
** (EXIT from #PID<0.93.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in String.slice/3
        (elixir) lib/string.ex:1864: String.slice("<internal code removed>", 1610, -1)
        lib/credo/code/heredocs.ex:253: Credo.Code.Heredocs.pad_replaced_heredoc/2
        lib/credo/code/heredocs.ex:156: Credo.Code.Heredocs.parse_heredoc/5
        lib/credo/check/readability/max_line_length.ex:52: Credo.Check.Readability.MaxLineLength.run/2
        lib/credo/check/runner.ex:168: Credo.Check.Runner.do_run_check_on_single_source_file/3
        lib/credo/check/runner.ex:161: Credo.Check.Runner.run_check_on_single_source_file/3
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
```

and the other

```
** (EXIT from #PID<0.93.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in String.slice/3
        (elixir) lib/string.ex:1864: String.slice("<internal code removed>", 701, -2)
        lib/credo/code/heredocs.ex:253: Credo.Code.Heredocs.pad_replaced_heredoc/2
        lib/credo/code/heredocs.ex:156: Credo.Code.Heredocs.parse_heredoc/5
        lib/credo/check/readability/max_line_length.ex:52: Credo.Check.Readability.MaxLineLength.run/2
        lib/credo/check/runner.ex:168: Credo.Check.Runner.do_run_check_on_single_source_file/3
        lib/credo/check/runner.ex:161: Credo.Check.Runner.run_check_on_single_source_file/3
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
```

**Comment by skovmand** [comment]
I have tried to isolate the error, and ended up with this minimal file to reproduce the issue.

The error goes away by doing either one of these things:
- Deleting `@some_utf_8_char`
- Removing the body of the regular expression (`([a-zæøå]+)`)
- Removing the last `@doc` block

```
defmodule CredoIssue.FailingFile do
  @some_utf8_char "💩"

  def match_whatever([whatever]) do
    case Regex.run(~r/([a-zæøå]+)/, whatever) do
      # Nothing here
    end
  end

  @doc """
  Nothing to see here really
  """
  def nothing_to_nil() do
    nil
  end
end
```

The stacktrace is:

```
** (EXIT from #PID<0.93.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in String.slice/3
        (elixir) lib/string.ex:1864: String.slice("defmodule CredoIssue.FailingFile do\n  @some_utf8_char \"💩\"\n\n  def match_whatever([whatever]) do\n    case Regex.run(~r/([a-zæøå]+)/, whatever) do\n      # Nothing here\n    end\n  end\n\n  @doc \"\"\"\n\n", 193, -1)
        lib/credo/code/heredocs.ex:253: Credo.Code.Heredocs.pad_replaced_heredoc/2
        lib/credo/code/heredocs.ex:156: Credo.Code.Heredocs.parse_heredoc/5
        lib/credo/check/readability/max_line_length.ex:52: Credo.Check.Readability.MaxLineLength.run/2
        lib/credo/check/runner.ex:168: Credo.Check.Runner.do_run_check_on_single_source_file/3
        lib/credo/check/runner.ex:161: Credo.Check.Runner.run_check_on_single_source_file/3
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
```

**Comment by skovmand** [comment]
And now the same minimal file reproduced from my other failing module

The weird part here is that the issue can be resolved by removing any of the characters `æøå` from the `@danish_words` list. I found that the module only crashes if there are 6 characters of type `æøå`, if one is removed, the error disappears.

Try for example to replace the `@danish_words`  list to `["åååååå"]`, and it still fails. Change it to five `å` characters and it the error disappears.

Removing the `@doc` block removes the error too.
```
defmodule CredoIssue.FailingFile2 do
  @danish_words [
    "Rødbede",
    "Æble",
    "Kål",
    "Kålorm",
    "Æblegrød"
  ]

  @doc """
  Just nil it!!
  """
  def nil_it() do
    nil
  end
end

```

**Comment by skovmand** [comment]
I suspect that it has something to do with the different `byte_size`s of the involved international characters and emojis, since:

```
iex(5)> byte_size("a") 
1
iex(6)> byte_size("å") 
2
iex(7)> byte_size("💩")
4
```

**Comment by k-cross** [comment]
I also have this issue on elixir 1.7.3

**Comment by robertpeacock22** [comment]
Here is the smallest repro I can come up with for this issue:
```
defmodule UnicodeTest do
  @x "fédération fédération fédération"

  @doc """
  """
end
```

This results in a similar stack trace to the one seen above:
```
** (FunctionClauseError) no function clause matching in String.slice/3
    (elixir) lib/string.ex:1741: String.slice("defmodule UnicodeTest do\n  @x \"fédération fédération fédération\"\n\n  @doc \"\"\"\n", 79, -2)
    lib/credo/code/heredocs.ex:253: Credo.Code.Heredocs.pad_replaced_heredoc/2
    lib/credo/code/heredocs.ex:156: Credo.Code.Heredocs.parse_heredoc/5
    lib/credo/check/readability/max_line_length.ex:52: Credo.Check.Readability.MaxLineLength.run/2
    lib/credo/check/runner.ex:168: Credo.Check.Runner.do_run_check_on_single_source_file/3
    lib/credo/check/runner.ex:161: Credo.Check.Runner.run_check_on_single_source_file/3
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
Function: #Function<9.36871822/0 in Credo.Check.Runner.run/2>
    Args: []
```

**Comment by rrrene** [comment]
Thx for reporting this! :+1: It should be be fixed in the latest version of Credo.

If it is not, please feel free to re-open this issue!

**Comment by jamesotron** [comment]
I'm really sorry to report that it's still happening:

```
$ mix credo --strict
Checking 19 source files ...

info: the following checks were skipped because they're not compatible with
your version of Elixir (1.9.0).

   1) Credo.Check.Refactor.MapInto
   2) Credo.Check.Warning.LazyLogging

Error while running Elixir.Credo.Check.Readability.MaxLineLength on lib/angle/dms.ex

07:56:00.170 [error] Task #PID<0.142.0> started from #PID<0.92.0> terminating
** (FunctionClauseError) no function clause matching in String.slice/3
    (elixir) lib/string.ex:1864: String.slice("defmodule Angle.DMS do\n  import Angle.Utils, only: [string_to_integer: 1, string_to_number: 1]\n  alias Angle.Degree\n\n  @moduledoc \"\"\"\n\n\"\"\"\n\n  @parser ~r/(-?[0-9]+)\n             (?:[\\x{00b0},\\ ]?\\ *)\n             ([0-9]+)\n             (?:[\\x{2032}',\\ ]?\\ *)\n             ([0-9]+(?:\\.[0-9]+)?)\n             [\\x{2033}\"]?/ux\n\n  @doc \"\"\"\n  Initialize an Angle from integer `d` degrees.\n\n  ## Examples\n\n      iex> init(13)\n      #Angle<13°>\n  \"\"\"\n\n\n\n\"\"\"\n  Initialize an Angle from integer `d` degrees, optionally followed by integer\n  `m` minutes.\n\n  ## Examples\n\n      iex> init(13, 30)\n      #Angle<13° 30′>\n  \"\"\"\n\n\n\n\"\"\"\n  Initialize an Angle from integer `d` degrees, followed by integer\n  `m` minutes and `s` seconds.\n\n  ## Examples\n\n      iex> init(13, 30, 45)\n      #Angle<13° 30′ 45″>\n  \"\"\"\n\n\n\n\n", 797, -1)
    lib/credo/code/heredocs.ex:253: Credo.Code.Heredocs.pad_replaced_heredoc/2
    lib/credo/code/heredocs.ex:156: Credo.Code.Heredocs.parse_heredoc/5
    lib/credo/check/readability/max_line_length.ex:52: Credo.Check.Readability.MaxLineLength.run/2
    lib/credo/check/runner.ex:168: Credo.Check.Runner.do_run_check_on_single_source_file/3
    lib/credo/check/runner.ex:161: Credo.Check.Runner.run_check_on_single_source_file/3
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
Function: #Function<9.89825571/0 in Credo.Check.Runner.run/2>
    Args: []
** (EXIT from #PID<0.92.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in String.slice/3
        (elixir) lib/string.ex:1864: String.slice("defmodule Angle.DMS do\n  import Angle.Utils, only: [string_to_integer: 1, string_to_number: 1]\n  alias Angle.Degree\n\n  @moduledoc \"\"\"\n\n\"\"\"\n\n  @parser ~r/(-?[0-9]+)\n             (?:[\\x{00b0},\\ ]?\\ *)\n             ([0-9]+)\n             (?:[\\x{2032}',\\ ]?\\ *)\n             ([0-9]+(?:\\.[0-9]+)?)\n             [\\x{2033}\"]?/ux\n\n  @doc \"\"\"\n  Initialize an Angle from integer `d` degrees.\n\n  ## Examples\n\n      iex> init(13)\n      #Angle<13°>\n  \"\"\"\n\n\n\n\"\"\"\n  Initialize an Angle from integer `d` degrees, optionally followed by integer\n  `m` minutes.\n\n  ## Examples\n\n      iex> init(13, 30)\n      #Angle<13° 30′>\n  \"\"\"\n\n\n\n\"\"\"\n  Initialize an Angle from integer `d` degrees, followed by integer\n  `m` minutes and `s` seconds.\n\n  ## Examples\n\n      iex> init(13, 30, 45)\n      #Angle<13° 30′ 45″>\n  \"\"\"\n\n\n\n\n", 797, -1)
        lib/credo/code/heredocs.ex:253: Credo.Code.Heredocs.pad_replaced_heredoc/2
        lib/credo/code/heredocs.ex:156: Credo.Code.Heredocs.parse_heredoc/5
        lib/credo/check/readability/max_line_length.ex:52: Credo.Check.Readability.MaxLineLength.run/2
        lib/credo/check/runner.ex:168: Credo.Check.Runner.do_run_check_on_single_source_file/3
        lib/credo/check/runner.ex:161: Credo.Check.Runner.run_check_on_single_source_file/3
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
```

**Comment by jnylen** [comment]
Same here. Still a issue in 1.1.0.

**Comment by bencode** [comment]
@jamesotron  it's ok for me!

use 1.1.1 and dont forget mix deps.get and mix deps.compile

**Comment by jamesotron** [comment]
You're right. My CI is caching the old version for some reason.
