### ISSUE TITLE
Credo crash on elixir 1.9

### ISSUE THREAD

**Issue by laibulle** [rrrene/credo#667]
### Environment

* Credo version (`mix credo -v`): `0.9.3`
* Erlang/Elixir version (`elixir -v`): 
```
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.0 (compiled with Erlang/OTP 22)
```
* Operating system: OSX

```elixir
Checking 395 source files (this might take a while) ...
Error while running Elixir.Credo.Check.Design.DuplicatedCode

15:59:14.855 [error] Task #PID<0.515.0> started from #PID<0.92.0> terminating
** (FunctionClauseError) no function clause matching in Inspect.Algebra.to_doc/2
    (elixir) lib/inspect/algebra.ex:276: Inspect.Algebra.to_doc({:__block__, [], [{:use, [], [{:__aliases__, [], [:Mix, :Config]}]}, {:config, [], [:internal_api, [env: {{:., [line: 10, column: 11], [{:__aliases__, [line: 10, column: 8], [:Mix]}, :env]}, [], []}, app_version: {{:., [line: 11, column: 36], [Access, :get]}, [], [{{:., [line: 11, column: 27], [{:__aliases__, [line: 11, column: 16], [:Mix, :Project]}, :config]}, [], []}, :version]}, graphiql: false]]}, {:config, [], [:internal_api, {:__aliases__, [], [:InternalApi, :Endpoint]}, [url: [host: "localhost"], secret_key_base: "xxxxxxxxxx", render_errors: [view: {:__aliases__, [], [:InternalApi, :ErrorView]}, accepts: {:sigil_w, [], [{:<<>>, [], ["html json"]}, []]}], pubsub: [name: {:__aliases__, [], [:InternalApi, :PubSub]}, adapter: {:__aliases__, [], [:Phoenix, :PubSub, :PG2]}]]]}, {:config, [], [:internal_api, :generators, [context_app: false]]}, {:config, [], [:sentry, [release: {{:., [line: 24, column: 32], [Access, :get]}, [], [{{:., [line: 24, column: 23], [{:__aliases__, [line: 24, column: 12], [:Mix, :Project]}, :config]}, [], []}, :version]}, included_environments: [:staging, :prod]]]}, {:import_config, [], [{:<<>>, [], [{:"::", [], [{{:., [line: 29, column: 16], [Kernel, :to_string]}, [], [{{:., [line: 29, column: 21], [{:__aliases__, [line: 29, column: 18], [:Mix]}, :env]}, [], []}]}, {:binary, [], nil}]}, ".exs"]}]}]}, %{__struct__: Inspect.Opts, base: :decimal, binaries: :infer, char_lists: :infer, charlists: :infer, limit: 50, pretty: false, printable_limit: 4096, safe: true, structs: true, syntax_colors: [], width: 80})
    lib/credo/check/design/duplicated_code.ex:201: Credo.Check.Design.DuplicatedCode.to_hash/1
    lib/credo/check/design/duplicated_code.ex:187: Credo.Check.Design.DuplicatedCode.collect_hashes/4
    (elixir) lib/macro.ex:251: Macro.traverse/4
    lib/credo/code.ex:38: Credo.Code.prewalk/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/credo/check/design/duplicated_code.ex:95: Credo.Check.Design.DuplicatedCode.duplicate_nodes/2
    lib/credo/check/design/duplicated_code.ex:47: Credo.Check.Design.DuplicatedCode.run/3
Function: #Function<7.28306184/0 in Credo.Check.Runner.run_checks_that_run_on_all/2>
    Args: []
** (EXIT from #PID<0.92.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Inspect.Algebra.to_doc/2
        (elixir) lib/inspect/algebra.ex:276: Inspect.Algebra.to_doc({:__block__, [], [{:use, [], [{:__aliases__, [], [:Mix, :Config]}]}, {:config, [], [:internal_api, [env: {{:., [line: 10, column: 11], [{:__aliases__, [line: 10, column: 8], [:Mix]}, :env]}, [], []}, app_version: {{:., [line: 11, column: 36], [Access, :get]}, [], [{{:., [line: 11, column: 27], [{:__aliases__, [line: 11, column: 16], [:Mix, :Project]}, :config]}, [], []}, :version]}, graphiql: false]]}, {:config, [], [:internal_api, {:__aliases__, [], [:InternalApi, :Endpoint]}, [url: [host: "localhost"], secret_key_base: "xxxxxxxxxxx", render_errors: [view: {:__aliases__, [], [:InternalApi, :ErrorView]}, accepts: {:sigil_w, [], [{:<<>>, [], ["html json"]}, []]}], pubsub: [name: {:__aliases__, [], [:InternalApi, :PubSub]}, adapter: {:__aliases__, [], [:Phoenix, :PubSub, :PG2]}]]]}, {:config, [], [:internal_api, :generators, [context_app: false]]}, {:config, [], [:sentry, [release: {{:., [line: 24, column: 32], [Access, :get]}, [], [{{:., [line: 24, column: 23], [{:__aliases__, [line: 24, column: 12], [:Mix, :Project]}, :config]}, [], []}, :version]}, included_environments: [:staging, :prod]]]}, {:import_config, [], [{:<<>>, [], [{:"::", [], [{{:., [line: 29, column: 16], [Kernel, :to_string]}, [], [{{:., [line: 29, column: 21], [{:__aliases__, [line: 29, column: 18], [:Mix]}, :env]}, [], []}]}, {:binary, [], nil}]}, ".exs"]}]}]}, %{__struct__: Inspect.Opts, base: :decimal, binaries: :infer, char_lists: :infer, charlists: :infer, limit: 50, pretty: false, printable_limit: 4096, safe: true, structs: true, syntax_colors: [], width: 80})
        lib/credo/check/design/duplicated_code.ex:201: Credo.Check.Design.DuplicatedCode.to_hash/1
        lib/credo/check/design/duplicated_code.ex:187: Credo.Check.Design.DuplicatedCode.collect_hashes/4
        (elixir) lib/macro.ex:251: Macro.traverse/4
        lib/credo/code.ex:38: Credo.Code.prewalk/3
        (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/credo/check/design/duplicated_code.ex:95: Credo.Check.Design.DuplicatedCode.duplicate_nodes/2
        lib/credo/check/design/duplicated_code.ex:47: Credo.Check.Design.DuplicatedCode.run/3
```

**Comment by laibulle** [comment]
Fixed in 1.1
