### ISSUE TITLE
Bug: Crash on Credo.Check.Readability.FunctionNames (v1.1.1 only)

### ISSUE THREAD

**Issue by mroach** [rrrene/credo#678]
### Environment

* Credo version (`mix credo -v`): `1.1.1`

* Erlang/Elixir version (`elixir -v`):
```
Erlang/OTP 21 [erts-10.3.5.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.2 (compiled with Erlang/OTP 21)
```

* Operating system: Dockerized Elixir 1.8-Alpine running on macOS host system `Linux 3d3a97e5f8c9 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 Linux`

### What were you trying to do?

1. Upgraded from credo `1.1.0` to `1.1.1`
2. Ran `credo --strict`

### Expected outcome

Credo passed with the previous version; expected clean upgrade.

### Actual outcome

```
Error while running Elixir.Credo.Check.Readability.FunctionNames on lib/features/catalog.ex
Error while running Elixir.Credo.Check.Readability.FunctionNames on lib/xrh/services/user_properties.ex
[error] Task #PID<0.835.0> started from #PID<0.93.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 38, column: 9], [{:property, [line: 38, column: 17], nil}]}. This protocol is implemented for: Postgrex.Query, Postgrex.Copy, Decimal, Version, Float, Date, DateTime, Time, Version.Requirement, URI, BitString, List, NaiveDateTime, Atom, Integer
    (elixir) /usr/local/src/elixir/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) /usr/local/src/elixir/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
    lib/credo/check/readability/function_names.ex:76: Credo.Check.Readability.FunctionNames.issues_for_name/5
    lib/credo/check/readability/function_names.ex:54: Credo.Check.Readability.FunctionNames.traverse/3
    (elixir) lib/macro.ex:286: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:252: Macro.do_traverse/4
Function: #Function<9.120143378/0 in Credo.Check.Runner.run/2>
    Args: []
[error] Task #PID<0.769.0> started from #PID<0.93.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 133, column: 9], [{:to_key, [line: 133, column: 17], [{{:., [line: 133, column: 28], [{:spec, [line: 133, column: 24], nil}, :id]}, [line: 133, column: 28], []}]}]}. This protocol is implemented for: Postgrex.Query, Postgrex.Copy, Decimal, Version, Float, Date, DateTime, Time, Version.Requirement, URI, BitString, List, NaiveDateTime, Atom, Integer
    (elixir) /usr/local/src/elixir/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) /usr/local/src/elixir/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
    lib/credo/check/readability/function_names.ex:76: Credo.Check.Readability.FunctionNames.issues_for_name/5
    lib/credo/check/readability/function_names.ex:54: Credo.Check.Readability.FunctionNames.traverse/3
    (elixir) lib/macro.ex:286: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:252: Macro.do_traverse/4
Function: #Function<9.120143378/0 in Credo.Check.Runner.run/2>
    Args: []
** (EXIT from #PID<0.93.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 38, column: 9], [{:property, [line: 38, column: 17], nil}]}. This protocol is implemented for: Postgrex.Query, Postgrex.Copy, Decimal, Version, Float, Date, DateTime, Time, Version.Requirement, URI, BitString, List, NaiveDateTime, Atom, Integer
        (elixir) /usr/local/src/elixir/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) /usr/local/src/elixir/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
        lib/credo/check/readability/function_names.ex:76: Credo.Check.Readability.FunctionNames.issues_for_name/5
        lib/credo/check/readability/function_names.ex:54: Credo.Check.Readability.FunctionNames.traverse/3
        (elixir) lib/macro.ex:286: anonymous fn/4 in Macro.do_traverse_args/4
        (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:252: Macro.do_traverse/4
```

### Code in question

Both files that credo crashed on the lines using `def unquote...` to generate functions. Here's an example:

```elixir
@properties ~w(legacy_switch beta_tester)a

for property <- @properties do
  @doc """
  Fetch the current state of the `#{property}` property.

  Returns `{:ok, value}` when successful.
  """
  @doc section: :generated_helpers
  @spec unquote(property)(user_id()) :: {:ok, property_value()}
  def unquote(property)(user_id) when is_integer(user_id) do
    get_user_property(user_id, unquote(property))
  end
end
```

### mix.lock diff

```diff
-  "credo": {:hex, :credo, "1.1.0", "e0c07b2fd7e2109495f582430a1bc96b2c71b7d94c59dfad120529f65f19872f", [:mix], [{:bunt, "~> 0.2.0", [hex: :bunt, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}], "hexpm"},
+  "credo": {:hex, :credo, "1.1.1", "1ca6d2adfbb007d55c821fd514b089d933b31b0b6a07252e621daa890b94bea6", [:mix], [{:bunt, "~> 0.2.0", [hex: :bunt, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}], "hexpm"},
```

**Comment by hl** [comment]
Same for me:

```
Error while running Elixir.Credo.Check.Readability.FunctionNames on lib/context.ex

11:16:30.864 [error] Task #PID<0.258.0> started from #PID<0.92.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 86, column: 11], [{{:., [line: 86, column: 19], [:erlang, :binary_to_atom]}, [line: 86, column: 19], [{:<<>>, [line: 86, column: 19], ["get_", {:"::", [line: 86, column: 25], [{{:., [line: 86, column: 25], [Kernel, :to_string]}, [line: 86, column: 25], [{:name, [line: 86, column: 27], nil}]}, {:binary, [line: 86, column: 25], nil}]}]}, :utf8]}]} of type Tuple
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
    lib/credo/check/readability/function_names.ex:76: Credo.Check.Readability.FunctionNames.issues_for_name/5
    lib/credo/check/readability/function_names.ex:54: Credo.Check.Readability.FunctionNames.traverse/3
    (elixir) lib/macro.ex:290: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1440: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1440: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:256: Macro.do_traverse/4
Function: #Function<9.89825571/0 in Credo.Check.Runner.run/2>
    Args: []
** (EXIT from #PID<0.92.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 86, column: 11], [{{:., [line: 86, column: 19], [:erlang, :binary_to_atom]}, [line: 86, column: 19], [{:<<>>, [line: 86, column: 19], ["get_", {:"::", [line: 86, column: 25], [{{:., [line: 86, column: 25], [Kernel, :to_string]}, [line: 86, column: 25], [{:name, [line: 86, column: 27], nil}]}, {:binary, [line: 86, column: 25], nil}]}]}, :utf8]}]} of type Tuple
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
        lib/credo/check/readability/function_names.ex:76: Credo.Check.Readability.FunctionNames.issues_for_name/5
        lib/credo/check/readability/function_names.ex:54: Credo.Check.Readability.FunctionNames.traverse/3
        (elixir) lib/macro.ex:290: anonymous fn/4 in Macro.do_traverse_args/4
        (elixir) lib/enum.ex:1440: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1440: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:256: Macro.do_traverse/4
```

Source file:  https://gist.github.com/hl/c535b594b24e858d0e5ccfff29280c7a

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by mroach** [comment]
@rrrene It's solved for me! Thanks for the fix!

**Comment by hl** [comment]
@rrrene it works, thanks!

**Comment by rrrene** [comment]
@mroach @hl Great. Credo `v1.1.2` contains the fix. :+1: Thanks again for reporting this bug!
