### ISSUE TITLE
Credo crash on elixir 1.9.1

### ISSUE THREAD

**Issue by tobiasamft** [rrrene/credo#685]
### Precheck

Related to #667 

### Environment

* Credo version (`mix credo -v`):
1.1.2

* Erlang/Elixir version (`elixir -v`):
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

* Operating system:
  - Linux
  - Docker, image: elixir:1.9.1-alpine

### What were you trying to do?
Running `mix credo --strict` within `elixir:1.9.1-alpine` container in Docker on Linux.

### Expected outcome
Credo passes without error

### Actual outcome
```
Error while running Elixir.Credo.Check.Design.DuplicatedCode

06:52:03.337 [error] Task #PID<0.170.0> started from #PID<0.93.0> terminating
** (FunctionClauseError) no function clause matching in Inspect.Algebra.to_doc/2
    (elixir) lib/inspect/algebra.ex:276: Inspect.Algebra.to_doc({:defmodule, [], [{:__aliases__, [], [:ApplicationEvents]}, [do: {:__block__, [], [{:def, [], [{:fire_merge_started, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_started]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:def, [], [{:fire_merge_successful, [], [{:workload, [], nil}, {:persisted_queue, [], nil}, {:merge_started_event, [], nil}]}, [do: {:__block__, [], [{:=, [], [{:merge_successful_event, [], nil}, {:event, [], []}]}, {:=, [], [{:duration, [], nil}, {:duration, [], [{{:., [], [{:merge_started_event, [], nil}, :timestamp]}, [], []}, {{:., [], [{:merge_successful_event, [], nil}, :timestamp]}, [], []}]}]}, {{:., [], [{:__aliases__, [], [:Publisher]}, :publish_success]}, [], [{:workload, [], nil}, {:persisted_queue, [], nil}]}, {{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_succeeded]}, [], [{:workload, [], nil}, {:persisted_queue, [], nil}, {:duration, [], nil}]}, {:merge_successful_event, [], nil}]}]]}, {:def, [], [{:fire_merge_failed, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:Publisher]}, :publish_error]}, [], [{:workload, [], nil}]}, {{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_failed]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:def, [], [{:fire_merge_dismissed, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_dismissed]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:def, [], [{:fire_merge_version_obsolete, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_version_obsolete]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:def, [], [{:fire_merge_queue_not_found, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_queue_not_found]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:def, [], [{:fire_merge_source_queues_empty, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_source_queues_empty]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:defp, [], [{:duration, [], [{:start_time, [], nil}, {:end_time, [], nil}]}, [do: {:-, [], [{{:., [], [{:__aliases__, [], [:DateTime]}, :to_unix]}, [], [{:end_time, [], nil}]}, {{:., [], [{:__aliases__, [], [:DateTime]}, :to_unix]}, [], [{:start_time, [], nil}]}]}]]}, {:defp, [], [{:event, [], nil}, [do: {:%{}, [], [timestamp: {{:., [], [{:__aliases__, [], [:DateTime]}, :utc_now]}, [], []}]}]]}]}]]}, %{__struct__: Inspect.Opts, base: :decimal, binaries: :infer, char_lists: :infer, charlists: :infer, limit: 50, pretty: false, printable_limit: 4096, safe: true, structs: true, syntax_colors: [], width: 80})
    lib/credo/check/design/duplicated_code.ex:184: Credo.Check.Design.DuplicatedCode.to_hash/1
    lib/credo/check/design/duplicated_code.ex:170: Credo.Check.Design.DuplicatedCode.collect_hashes/4
    (elixir) lib/macro.ex:251: Macro.traverse/4
    lib/credo/code.ex:43: Credo.Code.prewalk/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/credo/check/design/duplicated_code.ex:80: Credo.Check.Design.DuplicatedCode.duplicate_nodes/2
    lib/credo/check/design/duplicated_code.ex:47: Credo.Check.Design.DuplicatedCode.run/3
Function: #Function<10.120143378/0 in Credo.Check.Runner.run/2>
    Args: []
** (EXIT from #PID<0.93.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Inspect.Algebra.to_doc/2
        (elixir) lib/inspect/algebra.ex:276: Inspect.Algebra.to_doc({:defmodule, [], [{:__aliases__, [], [:ApplicationEvents]}, [do: {:__block__, [], [{:def, [], [{:fire_merge_started, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_started]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:def, [], [{:fire_merge_successful, [], [{:workload, [], nil}, {:persisted_queue, [], nil}, {:merge_started_event, [], nil}]}, [do: {:__block__, [], [{:=, [], [{:merge_successful_event, [], nil}, {:event, [], []}]}, {:=, [], [{:duration, [], nil}, {:duration, [], [{{:., [], [{:merge_started_event, [], nil}, :timestamp]}, [], []}, {{:., [], [{:merge_successful_event, [], nil}, :timestamp]}, [], []}]}]}, {{:., [], [{:__aliases__, [], [:Publisher]}, :publish_success]}, [], [{:workload, [], nil}, {:persisted_queue, [], nil}]}, {{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_succeeded]}, [], [{:workload, [], nil}, {:persisted_queue, [], nil}, {:duration, [], nil}]}, {:merge_successful_event, [], nil}]}]]}, {:def, [], [{:fire_merge_failed, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:Publisher]}, :publish_error]}, [], [{:workload, [], nil}]}, {{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_failed]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:def, [], [{:fire_merge_dismissed, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_dismissed]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:def, [], [{:fire_merge_version_obsolete, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_version_obsolete]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:def, [], [{:fire_merge_queue_not_found, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_queue_not_found]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:def, [], [{:fire_merge_source_queues_empty, [], [{:workload, [], nil}]}, [do: {:__block__, [], [{{:., [], [{:__aliases__, [], [:ApplicationEvents, :InfluxConnection]}, :send_merge_source_queues_empty]}, [], [{:workload, [], nil}]}, {:event, [], []}]}]]}, {:defp, [], [{:duration, [], [{:start_time, [], nil}, {:end_time, [], nil}]}, [do: {:-, [], [{{:., [], [{:__aliases__, [], [:DateTime]}, :to_unix]}, [], [{:end_time, [], nil}]}, {{:., [], [{:__aliases__, [], [:DateTime]}, :to_unix]}, [], [{:start_time, [], nil}]}]}]]}, {:defp, [], [{:event, [], nil}, [do: {:%{}, [], [timestamp: {{:., [], [{:__aliases__, [], [:DateTime]}, :utc_now]}, [], []}]}]]}]}]]}, %{__struct__: Inspect.Opts, base: :decimal, binaries: :infer, char_lists: :infer, charlists: :infer, limit: 50, pretty: false, printable_limit: 4096, safe: true, structs: true, syntax_colors: [], width: 80})
        lib/credo/check/design/duplicated_code.ex:184: Credo.Check.Design.DuplicatedCode.to_hash/1
        lib/credo/check/design/duplicated_code.ex:170: Credo.Check.Design.DuplicatedCode.collect_hashes/4
        (elixir) lib/macro.ex:251: Macro.traverse/4
        lib/credo/code.ex:43: Credo.Code.prewalk/3
        (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/credo/check/design/duplicated_code.ex:80: Credo.Check.Design.DuplicatedCode.duplicate_nodes/2
        lib/credo/check/design/duplicated_code.ex:47: Credo.Check.Design.DuplicatedCode.run/3
```

**Comment by nulian** [comment]
Need to disable duplicate code to use credo for now with elixir 1.9.

**Comment by joshuawscott** [comment]
I had this same error, but after removing the `_build` directory in my app, credo works without issue. I've been unable to replicate the problem since then. I did notice that running `mix credo` doesn't do any dependency checks or compiling when I changed versions, so perhaps that is the issue?

**Comment by mhanberg** [comment]
I just ran into this setting up CI with GH actions.

Credo stopped passing when I started caching the `_build` directory to cache the Dialyzer PLT.

**Comment by TheFirstAvenger** [comment]
@tobiasamft In your environment, Credo seems to be calling `Inspect.Algebra.to_doc/2` on this line:
https://github.com/rrrene/credo/blob/v1.1.2/lib/credo/check/design/duplicated_code.ex#L184
but the `%Inspect.Opts{}` that gets passed as the second argument is missing the `inspect_fun` attribute. That attribute was added in Elixir `1.9.0` which seems to indicate that your credo dep is compiled on a pre-1.9.0 version but then the code is run on a 1.9.0+ version. Can you let us know if clearing the `_build` directory resolves this issue?

**Comment by TheFirstAvenger** [comment]
@mhanberg if you are caching the `_build` directory, you need to make sure the Elixir and Erlang versions are in your cache key so it busts the cache on a version upgrade. Here is a good example of how to do that on CircleCI:
https://github.com/poanetwork/blockscout/blob/d7d242e44bb694099de5b7abfe186e51198bce45/.circleci/config.yml#L27-L38

**Comment by tobiasamft** [comment]
😞 Sorry @TheFirstAvenger I was not able to reproduce the behaviour. I noticed it while deploying a microservice running within the company I'm working at. By now the service does not even exist anymore.

**Comment by TheFirstAvenger** [comment]
@rrrene I think this one can close for now, it looks like stale build files is the cause, we can reopen if someone has a way to reproduce this which indicates otherwise.
