### ISSUE TITLE
Error on Elixir.Credo.Check.Consistency.SpaceInParentheses

### ISSUE THREAD

**Issue by marocchino** [rrrene/credo#701]
### Precheck

* For proposing a new feature, be sure to name your issue "Proposal: ..."
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`):
1.1.4
* Erlang/Elixir version (`elixir -v`):
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 20)
* Operating system:
macOS 10.14.6 (18G103)

### What were you trying to do?

`mix credo` in my project.

### Expected outcome

I want at least readable error output. I'm sorry about the rough report, but I don't know which part of my code is the problem.

### Actual outcome

```
Checking 18 source files ...
Error while running Elixir.Credo.Check.Consistency.SpaceInParentheses

10:40:25.537 [error] Task #PID<0.137.0> started from #PID<0.92.0> terminating
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must either be empty or only
contain the following elements:

  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

["\"", {{161, 57, nil}, {161, 62, nil}, [{:identifier, {161, 59, nil}, :key}]}, "\": \"", {{161, 67, nil}, {161, 72, nil}, [{:identifier, {161, 69, nil}, :val}]}, "\""]

    (elixir) lib/list.ex:912: List.to_string/1
    lib/credo/code/token.ex:251: Credo.Code.Token.PositionHelper.to_col_end/3
    lib/credo/code/token.ex:235: Credo.Code.Token.PositionHelper.convert_to_col_end/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/credo/code/token.ex:138: Credo.Code.Token.PositionHelper.position_tuple_for_quoted_string/3
    lib/credo/code** (EXIT from #PID<0.92.0>) an exception was raised:
    ** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must either be empty or only
contain the following elements:

  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

["\"", {{161, 57, nil}, {161, 62, nil}, [{:identifier, {161, 59, nil}, :key}]}, "\": \"", {{161, 67, nil}, {161, 72, nil}, [{:identifier, {161, 69, nil}, :val}]}, "\""]

        (elixir) lib/list.ex:912: List.to_string/1
        lib/credo/code/token.ex:251: Credo.Code.Token.PositionHelper.to_col_end/3
        lib/credo/code/token.ex:235: Credo.Code.Token.PositionHelper.convert_to_col_end/3
        (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/credo/code/token.ex:138: Credo.Code.Token.PositionHelper.position_tuple_for_quoted_string/3
        lib/credo/code/interpolation_helper.ex:198: Credo.Code.InterpolationHelper.find_interpolations/2
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2

/interpolation_helper.ex:198: Credo.Code.InterpolationHelper.find_interpolations/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
Function: #Function<10.89825571/0 in Credo.Check.Runner.run/2>
    Args: []
```

**Comment by marocchino** [comment]
It was 

```elixir
"unexpected params: #{
       Enum.map_join(params, ", ", fn {key, val} -> ~s{"#{key}": "#{val}"} end)
     }"
```

**Comment by rrrene** [comment]
Thx for reporting this :+1:

**Comment by TheFirstAvenger** [comment]
This is a duplicate of https://github.com/rrrene/credo/issues/681 caused by the sigil inside the string interpolation. It was fixed in https://github.com/rrrene/credo/commit/0a2a89442d3633799b457a285aba851dd6b3d04f

**Comment by TheFirstAvenger** [comment]
@marocchino can you verify it works for you in the latest version and close if so?

**Comment by marocchino** [comment]
I checked with Credo 1.1.5 with the same syntax and no errors. Thank you.
