### ISSUE TITLE
Credo crash after migration to elixir 1.11

### ISSUE THREAD

**Issue by tino415** [rrrene/credo#842]
### Precheck

* Credo start crashing after migration to elixir 1.11 (unable to find exact code that causes it)

### Environment

* Credo version (`mix credo -v`): 1.4.0
* Erlang/Elixir version (`elixir -v`): 23/1.11.2
* Operating system: Mac OSX Catalina 10.15.7

### What were you trying to do?

Run `mix credo`

### Expected outcome

Protocol from ecto checks

### Actual outcome

```
~$ mix credo
Checking 145 source files (this might take a while) ...
** (config) Error while running Elixir.Credo.Check.Consistency.SpaceAroundOperators

12:03:08.262 [error] Task #PID<0.399.0> started from #PID<0.94.0> terminating
** (FunctionClauseError) no function clause matching in Credo.Code.Token.PositionHelper.position/1
    lib/credo/code/token.ex:49: Credo.Code.Token.PositionHelper.position({:sigil, {47, 71, nil}, 76, [""], [], nil, "\""})
    lib/credo/check/consistency/space_around_operators/space_helper.ex:58: Credo.Check.Consistency.SpaceAroundOperators.SpaceHelper.no_space_between?/2
    lib/credo/check/consistency/space_around_operators/collector.ex:166: Credo.Check.Consistency.SpaceAroundOperators.Collector.without_space?/3
    lib/credo/check/consistency/space_around_operators/collector.ex:130: Credo.Check.Consistency.SpaceAroundOperators.Collector.record_spaces/4
    lib/credo/check/consistency/space_around_operators/collector.ex:37: Credo.Check.Consistency.SpaceAroundOperators.Collector.traverse_tokens/3
    lib/credo/check/consistency/collector.ex:140: anonymous fn/3 in Credo.Check.Consistency.Collector.find_issues/4
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
Function: #Function<10.46020751/0 in Credo.Check.Runner.run/2>
    Args: []
** (EXIT from #PID<0.94.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Credo.Code.Token.PositionHelper.position/1
        lib/credo/code/token.ex:49: Credo.Code.Token.PositionHelper.position({:sigil, {47, 71, nil}, 76, [""], [], nil, "\""})
        lib/credo/check/consistency/space_around_operators/space_helper.ex:58: Credo.Check.Consistency.SpaceAroundOperators.SpaceHelper.no_space_between?/2
        lib/credo/check/consistency/space_around_operators/collector.ex:166: Credo.Check.Consistency.SpaceAroundOperators.Collector.without_space?/3
        lib/credo/check/consistency/space_around_operators/collector.ex:130: Credo.Check.Consistency.SpaceAroundOperators.Collector.record_spaces/4
        lib/credo/check/consistency/space_around_operators/collector.ex:37: Credo.Check.Consistency.SpaceAroundOperators.Collector.traverse_tokens/3
        lib/credo/check/consistency/collector.ex:140: anonymous fn/3 in Credo.Check.Consistency.Collector.find_issues/4
        (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
        (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
```

**Comment by rrrene** [comment]
@tino415 Credo `1.4.0` is not compatible with Elixir `1.11`.

You will need to upgrade to Credo `1.4.1` or `1.5.x` :+1:
