### ISSUE TITLE
GenServer.call Credo.Service.SourceFileAST :put timeout

### ISSUE THREAD

**Issue by tielur** [rrrene/credo#860]
### Environment

* Credo version (`mix credo -v`): 1.4.1
* Erlang/Elixir version (`elixir -v`): Elixir 1.11.2 (compiled with Erlang/OTP 22)
* Operating system: AmazonLinux on CircleCI

### What were you trying to do?
`mix credo`

### Expected outcome
Credo completes and shows output

### Actual outcome
```
22:31:36.373 [error] Task #PID<0.417.0> started from #PID<0.94.0> terminating
** (stop) exited in: GenServer.call(Credo.Service.SourceFileAST, {:put, "lib/joint_registry/user_accounts/user_permission.ex", {:defmodule, [line: 1, column: 1], [{:__aliases__, [line: 1, column: 11], [:JointRegistry, :UserAccounts, :UserPermission]}, [do: {:__block__, [], [{:@, [line: 2, column: 3], [{:moduledoc, [line: 2, column: 4], ["This is the join table for users and permissions"]}]}, {:use, [line: 3, column: 3], [{:__aliases__, [line: 3, column: 7], [:Ecto, :Schema]}]}, {:schema, [line: 5, column: 3], ["users_permissions", [do: {:__block__, [], [{:belongs_to, [line: 6, column: 5], [:user, {:__aliases__, [line: 6, column: 23], [:JointRegistry, :UserAccounts, :User]}]}, {:belongs_to, [line: 7, column: 5], [:permission, {:__aliases__, [line: 7, column: 29], [:JointRegistry, :Permissions, :Permission]}]}, {:timestamps, [line: 9, column: 5], []}]}]]}]}]]}}, 5000)
    ** (EXIT) time out
    (elixir 1.11.2) lib/gen_server.ex:1027: GenServer.call/3
    lib/credo/source_file.ex:40: Credo.SourceFile.parse/2
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<6.53386202/0 in Credo.Sources.read_files/2>
    Args: []

22:31:36.074 [error] Task #PID<0.479.0> started from #PID<0.94.0> terminating
** (stop) exited in: GenServer.call(Credo.Service.SourceFileAST, {:put, "lib/joint_registry_web/views/access_gudid_view.ex", {:defmodule, [line: 1, column: 1], [{:__aliases__, [line: 1, column: 11], [:JointRegistryWeb, :AccessGudidView]}, [do: {:use, [line: 2, column: 3], [{:__aliases__, [line: 2, column: 7], [:JointRegistryWeb]}, :view]}]]}}, 5000)
    ** (EXIT) time out
    (elixir 1.11.2) lib/gen_server.ex:1027: GenServer.call/3
    lib/credo/source_file.ex:40: Credo.SourceFile.parse/2
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<6.53386202/0 in Credo.Sources.read_files/2>
    Args: []

22:31:36.074 [error] Task #PID<0.489.0> started from #PID<0.94.0> terminating
** (stop) exited in: GenServer.call(Credo.Service.SourceFileAST, {:put, "lib/joint_registry_web/views/forms/radio_view.ex", {:defmodule, [line: 1, column: 1], [{:__aliases__, [line: 1, column: 11], [:JointRegistryWeb, :Forms, :RadioView]}, [do: {:__block__, [], [{:@, [line: 2, column: 3], [{:moduledoc, [line: 2, column: 4], ["Helper methods for generating radio HTML for many-many associations\n"]}]}, {:use, [line: 6, column: 3], [{:__aliases__, [line: 6, column: 7], [:JointRegistryWeb]}, :view]}, {:@, [line: 8, column: 3], [{:doc, [line: 8, column: 4], ["Renders multiple radios for many-many associations.\n\n## Examples\n\n  radios_for_options(form, :procedure, [{\"Knee\", \"knee\"}])\n"]}]}, {:def, [line: 15, column: 3], [{:radios_for_options, [line: 15, column: 7], [{:form, [line: 15, column: 26], nil}, {:field, [line: 15, column: 32], nil}, {:options, [line: 15, column: 39], nil}]}, [do: {:render, [line: 16, column: 5], ["_radio_group.html", [form: {:form, [line: 18, column: 13], nil}, field: {:field, [line: 19, column: 14], nil}, options: {:options, [line: 20, column: 16], nil}]]}]]}]}]]}}, 5000)
    ** (EXIT) time out
    (elixir 1.11.2) lib/gen_server.ex:1027: GenServer.call/3
    lib/credo/source_file.ex:40: Credo.SourceFile.parse/2
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<6.53386202/0 in Credo.Sources.read_files/2>
    Args: []
```

**Comment by rrrene** [comment]
Ouch, that's odd. Thanks for reporting this :+1:

**Comment by nicklayb** [comment]
I'm not sure if that's related but I attempted writing my own check (following the guides from hexdocs) and I'm having the following error when running the tests

```
  1) test it should NOT report expected code (Credo.Check.Readability.SimpleTupleTest)
     test/credo/check/readability/simple_tuple_test.exs:6
     ** (exit) exited in: GenServer.call(Credo.Service.SourceFileAST, {:put, "1430B41004D43A4C9C7AE6EF29268078B0F81A327074F22737D796EF54C78180", {:defmodule, [line: 1, column: 1], [{:__aliases__, [line: 1, column: 11], [:CredoSampleModule]}, [do: {:def, [line: 2, column: 3], [{:function, [line: 2, column: 7], [{:value, [line: 2, column: 16], nil}]}, [do: {:__block__, [], [{:=, [line: 3, column: 11], [{:value, [line: 3, column: 5], nil}, {:|>, [line: 6, column: 7], [{:|>, [line: 5, column: 7], [{:value, [line: 4, column: 7], nil}, {{:., [line: 5, column: 14], [{:__aliases__, [line: 5, column: 10], [:Enum]}, :map]}, [line: 5, column: 14], [{:&, [line: 5, column: 19], [{:/, [line: 5, column: 35], [{{:., [line: 5, column: 26], [{...}, ...]}, [no_parens: true, line: 5, column: 26], []}, 1]}]}]}]}, {{:., [line: 6, column: 14], [{:__aliases__, [line: 6, column: 10], [:Enum]}, :join]}, [line: 6, column: 14], [""]}]}]}, {:ok, {:value, [line: 8, column: 11], nil}}]}]]}]]}}, 60000)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
     code: |> to_source_file()
     stacktrace:
       (elixir 1.11.4) lib/gen_server.ex:1017: GenServer.call/3
       (credo 1.5.5) lib/credo/source_file.ex:54: Credo.SourceFile.parse/2
       (credo 1.5.5) lib/credo/test/source_files.ex:9: Credo.Test.SourceFiles.to_source_file/2
       test/credo/check/readability/simple_tuple_test.exs:19: (test)



  2) test it should report code that includes rejected module attribute names (Credo.Check.Readability.SimpleTupleTest)
     test/credo/check/readability/simple_tuple_test.exs:24
     ** (exit) exited in: GenServer.call(Credo.Service.SourceFileAST, {:put, "D2218CC59F6703D6D987B96A2711F8089DD78BB8A2A7B7F7CB46827A92CA0BA5", {:defmodule, [line: 1, column: 1], [{:__aliases__, [line: 1, column: 11], [:CredoSampleModule]}, [do: {:def, [line: 2, column: 3], [{:function, [line: 2, column: 7], [{:value, [line: 2, column: 16], nil}]}, [do: {:ok, {:|>, [line: 7, column: 7], [{:|>, [line: 6, column: 7], [{:value, [line: 5, column: 7], nil}, {{:., [line: 6, column: 14], [{:__aliases__, [line: 6, column: 10], [:Enum]}, :map]}, [line: 6, column: 14], [{:&, [line: 6, column: 19], [{:/, [line: 6, column: 35], [{{:., [line: 6, column: 26], [{:__aliases__, [line: 6, column: 20], [:String]}, :downcase]}, [no_parens: true, line: 6, column: 26], []}, 1]}]}]}]}, {{:., [line: 7, column: 14], [{:__aliases__, [line: 7, column: 10], [:Enum]}, :join]}, [line: 7, column: 14], [""]}]}}]]}]]}}, 60000)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
     code: |> to_source_file()
     stacktrace:
       (elixir 1.11.4) lib/gen_server.ex:1017: GenServer.call/3
       (credo 1.5.5) lib/credo/source_file.ex:54: Credo.SourceFile.parse/2
       (credo 1.5.5) lib/credo/test/source_files.ex:9: Credo.Test.SourceFiles.to_source_file/2
       test/credo/check/readability/simple_tuple_test.exs:37: (test)



Finished in 0.03 seconds
2 tests, 2 failures

Randomized with seed 977148
```

The test file 

```elixir
defmodule Credo.Check.Readability.SimpleTupleTest do
  use Credo.Test.Case

  alias Credo.Check.Readability.SimpleTuple

  test "it should NOT report expected code" do
    """
    defmodule CredoSampleModule do
      def function(value) do
        value =
          value
          |> Enum.map(&String.downcase/1)
          |> Enum.join("")

        {:ok, value}
      end
    end
    """
    |> to_source_file()
    |> run_check(SimpleTuple)
    |> refute_issues()
  end

  test "it should report code that includes rejected module attribute names" do
    """
    defmodule CredoSampleModule do
      def function(value) do
        {
          :ok,
          value
          |> Enum.map(&String.downcase/1)
          |> Enum.join("")
        }
      end
    end
    """
    |> to_source_file()
    |> run_check(SimpleTuple)
    |> assert_issues()
  end
end
```

The check code:

```
defmodule Credo.Check.Readability.SimpleTuple do
  use Credo.Check,
    base_priority: :high,
    category: :readability,
    param_defaults: [],
    explanations: [
      check: """
      """,
      params: [reject: "This check warns about too complex tuple return."]
    ]

  def run(source_file, params \\ []) do
    []
  end
end
```

Credo version: 1.5.5
Elixir version: 1.11.4

**Comment by cheerfulstoic** [comment]
I just ran into the same issue as @nicklayb.  I stated writing a whole comment until I saw his edits at the bottom, so in case somebody else skips them like me, make sure to check if you need `runtime: false` in your `mix.exs` 😆

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.
