### ISSUE TITLE
Bunt missing when using standalone

### ISSUE THREAD

**Issue by aerosol** [rrrene/credo#97]
Hi,

I am trying to use Credo as stand alone.

```
$ mix hex.info
Hex:    0.12.1
Elixir: 1.2.2
OTP:    18.1.3

22:12:14 hq1@kosmos ~/dev
$ git clone git@github.com:rrrene/credo.git
...

22:12:18 hq1@kosmos ~/dev
$ cd credo

22:12:23 hq1@kosmos ~/dev/credo      [master]
$  mix deps.get
Running dependency resolution
* Getting bunt (Hex package)
  Checking package (https://repo.hex.pm/tarballs/bunt-0.1.5.tar)
  Using locally cached package
...

22:12:30 hq1@kosmos ~/dev/credo      [master-]
$ mix archive.build
==> bunt
Compiled lib/bunt.ex
Compiled lib/bunt_ansi.ex
Generated bunt app
...

22:14:57 hq1@kosmos ~/dev/myproject
$ mix credo
** (UndefinedFunctionError) undefined function Bunt.puts/1 (module Bunt is not available)
    Bunt.puts("Checking 370 source files (this might take a while) ...")
    lib/credo/cli/command/suggest.ex:19: Credo.CLI.Command.Suggest.run/2
    lib/credo/cli.ex:55: Credo.CLI.main/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2


22:15:00.916 [error] GenServer Credo.Supervisor terminating
** (UndefinedFunctionError) undefined function Bunt.puts/1 (module Bunt is not available)
    Bunt.puts("Checking 370 source files (this might take a while) ...")
    lib/credo/cli/command/suggest.ex:19: Credo.CLI.Command.Suggest.run/2
    lib/credo/cli.ex:55: Credo.CLI.main/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
    (elixir) src/elixir_lexical.erl:16: :elixir_lexical.run/3
    (elixir) src/elixir_compiler.erl:30: :elixir_compiler.quoted/3
    (elixir) lib/code.ex:363: Code.require_file/2
Last message: {:EXIT, #PID<0.46.0>, {%UndefinedFunctionError{arity: 1, function: :puts, module: Bunt, reason: nil}, [{Bunt, :puts, ["Checking 370 source files (this might take a while) ..."], []}, {Credo.CLI.Command.Suggest, :run, 2, [file: 'lib/credo/cli/command/suggest.ex', line: 19]}, {Credo.CLI, :main, 1, [file: 'lib/credo/cli.ex', line: 55]}, {Mix.CLI, :run_task, 2, [file: 'lib/mix/cli.ex', line: 58]}, {:elixir_compiler, :dispatch_loaded, 6, [file: 'src/elixir_compiler.erl', line: 125]}, {:elixir_lexical, :run, 3, [file: 'src/elixir_lexical.erl', line: 16]}, {:elixir_compiler, :quoted, 3, [file: 'src/elixir_compiler.erl', line: 30]}, {Code, :require_file, 2, [file: 'lib/code.ex', line: 363]}]}}
State: {:state, {:local, Credo.Supervisor}, :one_for_one, [{:child, #PID<0.71.0>, Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {:child, #PID<0.70.0>, Credo.Service.SourceFileCodeOnly, {Credo.Service.SourceFileCodeOnly, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileCodeOnly]}, {:child, #PID<0.69.0>, Credo.Service.SourceFileWithoutStringAndSigils, {Credo.Service.SourceFileWithoutStringAndSigils, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileWithoutStringAndSigils]}], :undefined, 3, 5, [], Supervisor.Default, {:ok, {{:one_for_one, 3, 5}, [{Credo.Service.SourceFileWithoutStringAndSigils, {Credo.Service.SourceFileWithoutStringAndSigils, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileWithoutStringAndSigils]}, {Credo.Service.SourceFileCodeOnly, {Credo.Service.SourceFileCodeOnly, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileCodeOnly]}, {Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}]}}}
```

Where do I go from here?

**Comment by rrrene** [comment]
Try to install `bunt` as an archive as well. That should probably work (I hope).

**Comment by carakan** [comment]
I had the same error when I'm trying to install as standalone, one solution is install blunt also as standalone, I made some instructions in my pronto gem integration https://github.com/carakan/pronto-credo#configuring-runner

**Comment by rrrene** [comment]
@carakan Cool, there is a part in my README where we try to explain it, but yours seems easier to understand. 

If you'd send a pull request for Credo's README with the added instructions, I would gladly accept it. :+1:
